### ISSUE TITLE
Playback thread be killed immediately after run aplay.

### ISSUE THREAD

**Issue by ZhendanYang** [thesofproject/sof#273] opened 2018-08-29 09:03 UTC
Summary:
playback will be killed immediately after I run "aplay -D hw:0,0 -c 2 -r 48000 -f s16_le music.wav --period-size=192 --buffer-size=384 -vv -i", and we can find ipc time out in dmesg

Reproduce steps:
1. aplay -D hw:0,0 -c 2 -r 48000 -f s16_le music.wav --period-size=192 --buffer-size=384 -vv -i
2. terminal will show "killed" and then dmesg
(It can not easily reproduce on up^2, but more easy to reprodude on GP)

Environment:
on two apl platforms, below is environment on up^2
sof ： 
stable 1.2 : 7346243e596cd91ff4342308e680392600496b3a on up^2
glk-003-branch 678cf3f655be73becc937878ac79236f2a07f456 on GP       
soft ： 41861aac373eb1f6978bfdb0bbe97cd882b1785a
sof-dev : f9c923e5ca9b38df7ddc71f26b55eb2bd1ffed46
tplg: sof-apl-nocodec.tplg, sof-apl-tdf8532.tplg

Log：
[dmesg-killed.log](https://github.com/thesofproject/sof/files/2331377/dmesg-killed.log)
[rmbox-t-killed.log](https://github.com/thesofproject/sof/files/2331378/rmbox-t-killed.log)

**Comment by lgirdwood** [comment] 2018-08-29 09:26
This looks like two issues. 

@zhigang-wu  driver error handling code in sof_pcm_close is deref a NULL pointer probably as part of cleanup.
@RanderWang the FW part could be related to the scheduler. Can we try this with your new fix.

**Comment by zhigang-wu** [comment] 2018-08-29 09:27
@lgirdwood 
OK, I will move on this to root cause it.

**Comment by zhigang-wu** [comment] 2018-08-30 08:03
the kernel panic's root cause is found:
1. when the DSP firmware has problems: ipc timeout, it will stop the sof' resume process.
    then the pointer of substream->runtime->private_data will not be allocated.
2. because of the resume process stopped, the suspend operation will start.
    the suspend process will enter the hda_dsp_pcm_close() function to access this NULL pointer.
    the kernel panic issue will happened.
3. in normal process, our kernel's driver (pm feature) will have not this issue. but for the DSP's 
    problem, it trigger the abnormal process. but we did not handle it correctly.

I will check more code to figure out a better solution for this kernel's issue.

**Comment by lgirdwood** [comment] 2018-08-30 09:26
@zhigang-wu lets check this is suspend process, if its NULL then we just return an error and dont suspend.

**Comment by ZhendanYang** [comment] 2018-09-10 06:05
Can't be reproduced on stable-1.2 branch. Test on GLK-003 is blocked by issue #263 .

**Comment by mengdonglin** [comment] 2018-09-17 15:48
Close this issue because all generic fixes on glk-003 branch have been merged by master.  So testing with master branch will be okay for mature platforms. glk release branch does not focus on compatibility across platforms. 

@ZhendanYang please reopen it if this issue can be reproduced by master branch.

**Closed by mengdonglin** 2018-09-17 15:48 UTC
Labels: APL, P3, br-glk, bug, duplicate, regression
