### ISSUE TITLE
[BUG] [TGL] HDA controller reset fails in reboot tests

### ISSUE THREAD

**Issue by sathya-nujella** [thesofproject/sof#3633] opened 2020-11-22 05:23 UTC
**[Bug cloned from]**
https://github.com/thesofproject/linux/issues/2571

DUT: TGL Chrome DUT with Max98373_RT5682 **I2S**
BIOS: Coreboot

**Issue:**
Sound card creation failed.

TEST SCENARIO:
Random scenarios.
one such scenario is:
Boot DUT -> mount file system -> reboot few times to see error.

****More details:****
**ISSUE REPRODUCED WITH:** 
SOF branch: tgl-011-drop-stable   top commit:  27aab4f83c187701bc17b037b39e9453ea0731d0

**After reverting the below patch, issue is not seen in 100 reboot cycles (need to continue further tests):**
tgl: enable WOVCRO clock
Reverted the patch:  https://github.com/thesofproject/sof/commit/75561a99642c50265ffb9f94a760e52e6a2e292b

**Comment by kv2019i** [comment] 2020-11-22 19:11
Hit on Ubuntu Linux device as well. FW 010-hotfix.

@abonislawski Would it be possible to change to a higher clock whenever DSP is stopped? It would seem that if clock is left at WOVCRO and system is reset, HDA controller will not come out of reset anymore (with high repro rate).

**Comment by keqiaozhang** [comment] 2020-11-23 02:18
we also observed this issue when testing sof-011-drop-stable branch,  I tried to test more on TGL-RVP-HDA this morning and found that the reproduction rate is about about 30%。

**Comment by mwasko** [comment] 2020-11-23 10:02
Is the FW even loaded when this reboot issue occurs?

**Comment by mengdonglin** [comment] 2020-11-23 10:30
Thank you @kv2019i and @keqiaozhang 

@abonislawski @mwasko Please note this issue can also be reproduced on branch tgl-010-drop-stable  and tgl-010-hot-fix-1, it's not a branch specific issue for tgl-011-drop-stable

**Comment by lgirdwood** [comment] 2020-11-23 10:36
@sathya-nujella @kv2019i I assume FW with reverted https://github.com/thesofproject/sof/commit/75561a99642c50265ffb9f94a760e52e6a2e292b has booted at least once (without a power OFF - due to the reproduction rates)  during your testing.
@mwasko it does seem that FW is booting, but I wonder if weed to force the clock in our FW D3 code to be sure (since it looks like the clock setting may survive a DSP D3).

**Comment by abonislawski** [comment] 2020-11-23 10:50
@kv2019i @lgirdwood do you think disabling wovcro in ipc_pm_context_save() (pm_prepare_D3) would be a good idea to test?

**Comment by lgirdwood** [comment] 2020-11-23 11:35
> @kv2019i @lgirdwood do you think disabling wovcro in ipc_pm_context_save() (pm_prepare_D3) would be a good idea to test?
> EDIT: but we already did on wakeup

@abonislawski it's probably worth trying (and remember any delay).

**Comment by kv2019i** [comment] 2020-11-23 13:03
@lgirdwood wrote:
> @sathya-nujella @kv2019i I assume FW with reverted [75561a9](https://github.com/thesofproject/sof/commit/75561a99642c50265ffb9f94a760e52e6a2e292b) has booted at least once (without a power OFF - due to the reproduction rates) during your testing.

Correct. DSP is loaded at least once, and then a sw-reset (system reboot) is performed.

**Comment by mengdonglin** [comment] 2020-11-24 01:15
Link the original PR to enable WOVCRO clock of @abonislawski:  https://github.com/thesofproject/sof/pull/3418

**Comment by keyonjie** [comment] 2020-11-24 07:02
> This issue cannot be reproduced with cold reboot(power-cycle), only happens with warm reboot.

Thanks, this is useful information. @kv2019i you are right, it is reproduced with the sw-reset only.

**Comment by mengdonglin** [comment] 2020-11-24 08:45
PR #3641 is trying to fix this blocker issue before an official BIOS fix for WOVCRO clock is available. Will perform stress test on this PR #3641

**Comment by mengdonglin** [comment] 2020-11-25 12:36
@keyonjie also submitted an extra kernel fix https://github.com/thesofproject/linux/pull/2581, which sets DSP back to D0 before reboot if it is at D0i3, to fix the boot fail issue at the consequent rebooting.

**Comment by abonislawski** [comment] 2020-11-25 13:21
@keyonjie @mengdonglin is PR #3641 still needed? Looks like this kernel fix will prevent from boot fail (forced hpro before reboot) and we can fully use wovcro as previously, is that right?

**Comment by keyonjie** [comment] 2020-11-26 03:05
> @keyonjie @mengdonglin is PR #3641 still needed? Looks like this kernel fix will prevent from boot fail (forced hpro before reboot) and we can fully use wovcro as previously, is that right?

@abonislawski as the IP owner mentioned, it is recommend to use WOVCRO for WoV only, or even for WoV in S0Ix only, so I would suggest to keep PR #3641 also.

**Comment by slawblauciak** [comment] 2021-02-26 11:29
@sathya-nujella is the issue still reproducible on the latest tgl-011-drop-stable branch?

**Comment by sathya-nujella** [comment] 2021-02-26 15:55
> @sathya-nujella is the issue still reproducible on the latest tgl-011-drop-stable branch?

Hi @slawblauciak ,

we have taken this PR : inux/pull/2581 to chrome kernel. With this we don't have issue [Issue is not reported in past 3~4 BKC cycles].

If kernel does not have the change, even with latest tgl-011 branch: issue is reproducible if reboot happens with wov stream open.

**Comment by keyonjie** [comment] 2021-03-01 04:57
yes, @slawblauciak @sathya-nujella the fixes are already merged to mainline kernel, let's close the issue. @sathya-nujella please reopen it if needed.

**Closed by keyonjie** 2021-03-01 04:57 UTC
Labels: P1, TGL, bug
