### ISSUE TITLE
[BUG]Regression. MixInMixOut. Silent in captured files

### ISSUE THREAD

**Issue by wszypelt** [thesofproject/sof#7072] opened 2023-02-10 11:10 UTC
**Describe the bug**
![image](https://github.com/intel-innersource/drivers.audio.firmware.converged/assets/102149194/37ced0a1-97d2-4399-b95d-80bdadd60dc0)

TEST DESCRIPTION:
        Transfer data with Mix In -> maximum number of MixOuts test as host-host loopback.
        MixIn -> multiple MixOuts is used in Linux topology.

        Tested Topology:
        +----+  +--------------------+   +--------------------+
        |    |  | +------+   +-----+ |   | +------+  +------+ |       1
        |    |--->|Copier|-->|MixIn|---+-->|MixOut|->|Copier|--------->+
        |    |  | +------+   +-----+ | | | +------+  +------+ |        |
        |    |  +--------------------+ | +--------------------+        |
        |    |                         |                               |
        |    |                         | ...                           |
        |    |                         |                               |
        |    |                         | +--------------------+        |
        |    |                         | | +------+  +------+ |   N    |
        |    |                         +-->|MixOut|->|Copier|----->|   |
        |    |                           | +------+  +------+ |    |   |
        |HOST|                           +--------------------+    |   |
        |    |                                                     |   |
        |    |  N                                                  |   |
        |    |<--------------------------------------------------- |   |
        |    |                                                         |
        |    |...                                                      |
        |    |                                                         |
        |    | 1                                                       |
        |    |<-------------------------------------------------------+|
        |    |
        |    |
        +----+

        _____________________
        TEST STEPS:
        1. Load FW
        2. Generate playback file
        3. Build topology
        4. Run all pipelines concurrently
        5. Wait for playback stream to finish
        6. Stop all pipelines concurrently
        8. Verify recorded files
        _____________________
        ACCEPTANCE CRITERIA:
        ·       No errors during test
        ·       Successful output files verification

**To Reproduce**
pytest -s "tests/avs/fw_01_base_fw_modules/test_18_mixers_topologies.py::TestMixinMixout::test_01_18_mixers_max_outputs[channel_count_8-mixout_count_3]"
**Reproduction Rate**
100%

**Impact**
After Bisect:
Last passed: SOF_FW_MASTER_01.01.00.4022 (https://quickbuild.igk.intel.com/build/11180522) 2023-01-05 23:31:54
First failed: SOF_FW_MASTER_01.01.00.4025 (https://quickbuild.igk.intel.com/build/11184576) 2023-01-06 23:31:34

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {SHA}
    * SOF: [SOF_FW_MASTER_01.01.00.4059
3) Name of the platform(s) on which the bug is observed.
    * Platform: MTL RVP

**Screenshots or console output**
[logsmixer.zip](https://github.com/thesofproject/sof/files/10706829/logsmixer.zip)

**Comment by wszypelt** [comment] 2023-02-10 11:15
@ranj063 Can you look at this bug? I think it could be your changes

**Comment by mengdonglin** [comment] 2023-03-13 09:01
@wszypelt Can you please clarify which commit introduced this regression?
There are updates on module adapter and Zephyr: 
Last Passed: https://quickbuild.igk.intel.com/build/11180522/log
First Failed: https://quickbuild.igk.intel.com/build/11184576/log
![image](https://user-images.githubusercontent.com/8703742/224650188-269ee6f3-236d-484d-9e16-15baa420d97e.png)

**Comment by wszypelt** [comment] 2023-03-13 09:35
@mengdonglin Okay, this will take some time(~24h), but I'll try to clarify which commit introduced this regression

**Comment by wszypelt** [comment] 2023-03-14 09:17
@abonislawski  already found the exact commit that causes this: thesofproject/sof@fba35b1

**Comment by lgirdwood** [comment] 2023-03-14 10:59
@ranj063 can you check, looks like we are not copying data for capture.

**Comment by wszypelt** [comment] 2023-04-21 08:07
@ranj063 any update?

**Comment by lgirdwood** [comment] 2023-04-28 11:02
@ranj063 @singalsu @andrula-song can someone comment here and take a look

**Comment by paulstelian97** [comment] 2023-04-28 11:15
This sounds eerily similar to the bug we fixed on IPC3 with https://github.com/thesofproject/sof/pull/7420

**Comment by lgirdwood** [comment] 2023-05-04 15:32
> This sounds eerily similar to the bug we fixed on IPC3 with #7420 + #7357 + #7264

@wszypelt does this resolve the issue for us ?

**Comment by ranj063** [comment] 2023-05-04 16:50
@wszypelt @mwasko I have tested a mixin-mixout in the capture path and I able to to capture the played audio file with SSP 1 loopback. The topology I tested is as below: As you can see On pipeline 10 there's a mixin-mixout in the path:
![sof-tgl-nocodec](https://user-images.githubusercontent.com/7766921/236271900-4857e12f-a125-4bba-8668-fd728049998b.png)

**Comment by fredoh9** [comment] 2023-05-04 18:01
I tried with yesterday daily build (SOF SHA1 is 1236f9d8f18a) and above Ranjani's tplg. I can see Ranjani's tplg has MixIn/MixOut in Pipeline 10, daily build doesn't have them.

I tested loopback test with SSP0 and SSP1. I have very decent loopback waveform for BOTH with daily build and with Ranjani's TPLG. Is this fixed after merged with https://github.com/thesofproject/sof/pull/7420 + https://github.com/thesofproject/sof/pull/7357 + https://github.com/thesofproject/sof/pull/7264 ?

**Comment by ranj063** [comment] 2023-05-04 22:06
@wszypelt Can you please share the SHA ID of the firmware commit you are testing? We can't seem to reproduce this with main. Or alternatively would you be able to retest with main?

**Comment by wszypelt** [comment] 2023-05-05 10:25
@ranj063 @lgirdwood @fredoh9 
Main SHA: 43b08c62b523f1d17cfb318a0c649a7ebafde913
I checked now on the latest main (SHA above) Unfortunately the error still reproduces

**Comment by mszleszy** [comment] 2023-05-08 14:19
@ranj063 @fredoh9 
Just a small clarification from my side. We see the problem only when using multiple sinks on same mixIn module (don't mistake with multi mixin modules)
like in here:
![image](https://user-images.githubusercontent.com/87766157/236847326-e8c9302e-807e-4865-940e-9c0cc4046aff.png)

In topologies mentioned before there are no pipelines using miltiple sinks on same mixin module, so no reproduction will be possible 

We don't see any problem when using only first sink, but when we bind anything to second sink, we receive only zero samples on all mixIn sinks

**Comment by lgirdwood** [comment] 2023-05-11 20:11
@ranj063 @fredoh9 any update ?

**Comment by ranj063** [comment] 2023-05-25 16:05
@mszleszy Thanks for the update. I will look into it today

**Comment by ranj063** [comment] 2023-05-25 21:03
@mszleszy I created a topology with 2 mixouts connected to the mix in the capture path as below and capture still works OK on Linux. I cannot create a host_copier->mix->mixout->host_copier on Linux as it just wont work.

![sof-tgl-nocodec](https://github.com/thesofproject/sof/assets/7766921/b5d05082-5bff-43de-bb63-86cba348fa41)

**Comment by mszleszy** [comment] 2023-05-30 10:58
@ranj063 

Unfortunately still having repro of the issue . I'm adding more details below
I took fw binary directly from 7693 PR.
When MixIn sinks end up on same MixOut module audio worked pretty well. 
But couldn't get same results on MixIn into two MixOut->hostCopier

For final confirmation I used additional i2s loop:
![image](https://github.com/thesofproject/sof/assets/87766157/35a8e48a-8eb1-4fe9-b142-1898f09a703a)

Still when using one sink I have proper data, after binding module to MixIn second sink, I have only zeros on all output pins
[ipc.log](https://github.com/thesofproject/sof/files/11599192/ipc.log)

**Comment by mszleszy** [comment] 2023-06-06 10:59
another update:
After https://github.com/thesofproject/sof/pull/7746  I'm able to run all possible MixIn counts but if MultiPipelineSetState has payload order as described in last comment. 
When running MixIn pipeline first and have 2 or more MixIn sink, I'm recording only zero samples.
I can change tests but I'm a bit afraid that I'll hide possible bug so need some architecture consultation

**Comment by pblaszko** [comment] 2023-06-12 07:27
> another update: After #7746 I'm able to run all possible MixIn counts but if MultiPipelineSetState has payload order as described in last comment. When running MixIn pipeline first and have 2 or more MixIn sink, I'm recording only zero samples. I can change tests but I'm a bit afraid that I'll hide possible bug so need some architecture consultation

Order of starting pipelines should not cause permanent problem with signal. Driver may start pipelines in various order.

**Comment by lrudyX** [comment] 2023-10-03 11:29
No longer reproduces 
![image](https://github.com/thesofproject/sof/assets/102149194/4f65f636-3378-4689-8a33-b28693b64934)

**Closed by lrudyX** 2023-10-03 11:29 UTC
Labels: bug, P2, IPC4, MTL
