### ISSUE TITLE
[BUG] Xrun on ADP_RVP_NOCODEC

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof#5469] opened 2022-03-03 22:02 UTC
**Describe the bug**

https://sof-ci.01.org/linuxpr/PR3338/build7261/devicetest/?model=ADLP_RVP_NOCODEC&testcase=multiple-pause-resume-5
````
(4/5) pcm'Port0' cmd'aplay' id'2': Wait for 22 ms before resume
                                                                           
                                                                            
 aplay: pcm_write:2086: write error: Input/output error

#+                                                 | 00%
=== PAUSE ===                                                            
(5/5) pcm'Port0 Deep Buffer' cmd'aplay' id'8': Wait for 39 ms before pause

(5/5) pcm'Port0 Deep Buffer' cmd'aplay' id'8': Wait for 47 ms before resume

2022-03-03 20:13:04 UTC [REMOTE_INFO] pipeline: Port0 with aplay
2022-03-03 20:13:04 UTC [REMOTE_INFO] pipeline: Port0 Deep Buffer with aplay
2022-03-03 20:13:04 UTC [REMOTE_INFO] Check expect exit status
declare -- cmd="journalctl_cmd --since=@1646338352"
2022-03-03 20:13:04 UTC [REMOTE_ERROR] pause resume PID 6074 had non-zero exit status
2022-03-03 20:13:04 UTC [REMOTE_ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
2022-03-03 20:13:04 UTC [REMOTE_ERROR]  die()  @  /home/ubuntu/sof-test/test-case/../case-lib/lib.sh
2022-03-03 20:13:04 UTC [REMOTE_ERROR]  main()  @  /home/ubuntu/sof-test/test-case/multiple-pause-resume.sh:191
2022-03-03 20:13:04 UTC [REMOTE_INFO] Starting /usr/local/bin/sof-logger -l /etc/sof/sof-adl.ldc -o /home/ubuntu/sof-test/logs/multiple-pause-resume/2022-03-03-20:12:40-25145/etrace.txt
2022-03-03 20:13:07 UTC [REMOTE_INFO] pkill -TERM sof-logger
Terminated
2022-03-03 20:13:08 UTC [REMOTE_INFO] nlines=47 /home/ubuntu/sof-test/logs/multiple-pause-resume/2022-03-03-20:12:40-25145/etrace.txt
2022-03-03 20:13:08 UTC [REMOTE_INFO] Test Result: FAIL!
````

**To Reproduce**

TPLG=/lib/firmware/intel/sof-tplg/sof-adl-nocodec.tplg MODEL=ADLP_RVP_NOCODEC ~/sof-test/test-case/multiple-pause-resume.sh -l 3 -r 5

**Reproduction Rate**
unclear, just observed this issue.

**Expected behavior**
No Xrun

**Impact**
showstopper.

**Environment**
Linux: 2528d9538dfd ASoC: SOF: sof-client: Allow the message injector for IPC4 as well
SOF: c42ede6a topology: sof-adl-max98360a-rt5682-waves: add new topology

2) Name of the topology file
    * Topology: sof-adl-nocodec.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: ADL_RVP_NOCODEC

@keqiaozhang @XiaoyunWu6666 FYI

**Comment by plbossart** [comment] 2022-03-04 17:44
@lgirdwood this needs to be on your radar for 2.1

**Comment by marc-hb** [comment] 2022-03-10 02:49
P1 because it was one of the most common failures in daily run 10879, reproduced on 3 ADL and 1 TGL system (10879?model=TGLH_RVP_NOCODEC_ZEPHYR&testcase=multiple-pause-resume-50)

I noticed a mixer in the middle of a pipeline on all failing systems. Is this an unsupported configuration and problem similar to this?
- https://github.com/thesofproject/sof-test/issues/866

Should some pipelines skipped like here?
- https://github.com/thesofproject/sof-test/pull/871

**Comment by mengdonglin** [comment] 2022-03-10 06:22
Comments by @keqiaozhang  "this issue has affected all ADLP and TGLU/H nocodec platforms. The reproduction rate has become extremely high now. " on 2022-03-09 UTC, report ID 10879. Both XTOS and Zephyr can reproduce this issue.

**Comment by lgirdwood** [comment] 2022-03-10 09:59
@keqiaozhang is there a bisect ? I'm trying to think of any recent pipeline or DMA changes, but it could be something else unrelated.

**Comment by lgirdwood** [comment] 2022-03-10 13:57
@keqiaozhang thanks - moving to P2 since it for pause. Not a rc1 blocker, but should fix for final.

**Comment by plbossart** [comment] 2022-03-10 14:35
So the question is really "why do we see an xrun on ADL_RVP" only, when the *same* topology is used across ALL cAVS platforms? Very surprising.

**Comment by kv2019i** [comment] 2022-03-10 16:03
@keqiaozhang @RanderWang  @lgirdwood @lyakh This could be caused by this IPC4 change:
8451fd8b17feb114cbecc2b12b3a3f62e64e0ac ("ipc4: fix pause issue with windows audio player")

.. the change in mixer_trigger_common() does not seem ok. So far the issue has not reproduce with this reverted, but I did have trouble to reproduce this earlier, so this is not conclusive yet. Please test this out.

**Comment by lyakh** [comment] 2022-03-11 07:58
> @keqiaozhang @RanderWang @lgirdwood @lyakh This could be caused by this IPC4 change: commit 8451fd8b17feb114cbecc2b12b3a3f62e64e0ac ("ipc4: fix pause issue with windows audio player") ... part of #5088
> 
> .. the change in mixer_trigger_common() does not seem ok. So far the issue has not reproduce with this reverted, but I did have trouble to reproduce this earlier, so this is not conclusive yet. Please test this out.

@kv2019i sorry, could you elaborate a bit? I don't see what that commit could be breaking for IPC3?

**Comment by kv2019i** [comment] 2022-03-11 08:09
@lyakh Ack, you are correct. I thought the patch changed the ordering of the dev->state change, but looking at it again, that's not the case.

**Comment by kv2019i** [comment] 2022-03-11 15:05
Continued the debug a bit and I can't find a flaw in mixer operation. Here's one case with some extra logs to mixer and dw-dma:

```
[       82066.246739] (        2000.104126) c2 mixer        1.0          src/audio/mixer.c:365  INFO mixer_copy wrote silence for 192 bytes
[       84066.350826] (        2000.104126) c2 mixer        1.0          src/audio/mixer.c:365  INFO mixer_copy wrote silence for 192 bytes
#  while the upstream PCMs are paused, mixer correctly provides silence data to the DAI (extra debugs above)
[       85758.954926] (        1692.604126) c0 ipc                  src/ipc/ipc3/handler.c:1585 INFO ipc: new cmd 0x60070000
# towards end of a 1ms tick, a RELEASE IPC is sent to both PCMs 
[       85789.423674] (          30.468748) c2 idc                ......./intel/cavs/idc.c:58   INFO idc_irq_handler(), IPC_IDCTFC_BUSY
[       85814.579923] (          25.156248) c2 idc                ......./intel/cavs/idc.c:186  INFO idc_do_cmd()
[       85837.548672] (          22.968750) c2 pipe         7.40  ....../pipeline-stream.c:261  INFO pipe trigger cmd 8
# release to PCM1
[       85880.152837] (          42.604164) c2 ll-schedule        ./schedule/ll_schedule.c:460  INFO task add 0xbe1d00c0 pipe-task <f11818eb-e92e-4082
-82a3-dc54c604ebb3>
[       85898.382003] (          18.229166) c2 ll-schedule        ./schedule/ll_schedule.c:464  INFO task params pri 0 flags 0 start 0 period 1000
[       85923.329919] (          24.947916) c2 ll-schedule        ./schedule/ll_schedule.c:365  INFO new added task->start 1005366549 at 1005364865
[       85940.673668] (          17.343750) c2 ll-schedule        ./schedule/ll_schedule.c:368  INFO num_tasks 2 total_num_tasks 4
[       86059.944497] (         119.270828) c2 mixer        1.0      src/audio/component.c:64   INFO comp_set_state(), state already set to 6
[       86091.038246] (          31.093748) c2 mixer        1.0      src/audio/component.c:64   INFO comp_set_state(), state already set to 5
[       86344.684069] (         253.645828) c0 ipc                  src/ipc/ipc3/handler.c:1585 INFO ipc: new cmd 0x60070000
[       86377.913234] (          33.229164) c2 idc                ......./intel/cavs/idc.c:58   INFO idc_irq_handler(), IPC_IDCTFC_BUSY
[       86402.236150] (          24.322916) c2 idc                ......./intel/cavs/idc.c:186  INFO idc_do_cmd()
[       86428.381982] (          26.145832) c2 pipe         11.55 ....../pipeline-stream.c:261  INFO pipe trigger cmd 8
# release to the other PCM
[       86470.673647] (          42.291664) c2 ll-schedule        ./schedule/ll_schedule.c:460  INFO task add 0xbe1d0180 pipe-task <f11818eb-e92e-4082
-82a3-dc54c604ebb3>
[       86489.006980] (          18.333332) c2 ll-schedule        ./schedule/ll_schedule.c:464  INFO task params pri 0 flags 0 start 0 period 1000
[       86513.694479] (          24.687498) c2 ll-schedule        ./schedule/ll_schedule.c:365  INFO new added task->start 1005404949 at 1005376199
[       86531.038228] (          17.343750) c2 ll-schedule        ./schedule/ll_schedule.c:368  INFO num_tasks 3 total_num_tasks 5
[       88197.496495] (        1666.458252) c2 mixer        1.0      src/audio/component.c:64   INFO comp_set_state(), state already set to 6
# processing the IPCs causes a notable gap in pipe scheduling, no audio is output from mixer during this time
[       88228.850661] (          31.354166) c2 mixer        1.0      src/audio/component.c:64   INFO comp_set_state(), state already set to 5
[       90330.360994] (        2101.510254) c2 mixer        1.0          src/audio/mixer.c:391  INFO mixer_copy(), source_bytes = 0xc0, sink_bytes = 0xc0
# here we finally send audio out from mixer, but it is too late and the link DMA runs out of data
[       90412.183907] (          81.822914) c2 dw-dma                 src/drivers/dw/dma.c:1128 ERROR dw_dma status 5
[       90432.652657] (          20.468750) c2 dw-dma                 src/drivers/dw/dma.c:1129 ERROR dw_dma avail 0 free 1536
[       90452.808906] (          20.156250) c2 dw-dma                 src/drivers/dw/dma.c:1130 ERROR dw_dma_get_data_size(): xrun detected
# DMA runs out of data from mixer and raises an xrun
```

Not yet sure how to fix this.

**Comment by lyakh** [comment] 2022-03-11 16:19
it would be interesting to find out whether mixer pipeline is scheduled at the ticks, when triggers are processed. IIUC the following should be happening here:
1. we have pipelines A and B mixed on a mixer, which represents pipeline C to the DAI
2. In the beginning A and B are paused, C is scheduled every 1ms and is copying silence to the DAI
3. RELEASE IPC arrives for A, the pipeline task is scheduled
4. on tick N that IPC is processed in that pipeline A task. *question* is pipeline C also still copying silence on this tick? Or what is it doing? Looks like not?
5. RELEASE IPC arrives for B, the pipeline task is scheduled
6. on tick N+1 (or is it still tick N?) that IPC is processed in that pipeline B task. *question* is pipeline C also still copying silence on this tick? Or what is it doing? Looks like it isn't streaming at all?

So, does it look like when IPCs are processed in pipeline A and B tasks the C pipeline task isn't sending anything to the DAI? This can be debugged - set a global flag when RELEASE IPCs arrive and when that flag is set print to trace. Maybe this bug triggers when RELEASE IPCs for pipelines A and B come too close to each other - within 1 scheduler tick?

**Comment by kv2019i** [comment] 2022-03-14 15:25
Thanks @lyakh  This was a good debugging approach. What seems to be happening in that when we handle the RELEASE IPC, the mixer-buffer-dai pipeline gets rescheduled (as a connected pipeline). Now this is problematic as DAI is already running and with suitable timing will lead to an xrun. 

I'm working on a fixes to make the transition of mixer sources from PAUSED to RELEASED, more robust. Basicly mixed should continue producing silence at regular pace until the sources start emitting data.

**Comment by keqiaozhang** [comment] 2022-03-22 02:12
Observed this issue on both APL_UP2_NOCODEC_ZEPHYR and CML_RVP_NOCODEC_ZEPHYR when testing multiple-pause-resume-50. Now all “NOCODEC_ZEPHYR” platforms are affected. 
Daily test ID: 11248.

**Comment by kv2019i** [comment] 2022-03-29 10:10
This issue still exists in Intel daily plan 11433, so the fix to #5556 has no impact to this case (this is expected).

**Comment by kv2019i** [comment] 2022-03-29 17:31
Returned to this issue today. I have found two issues -- first is a mixer logic issue related to how it handles its sources switching state to PAUSED in high frequency. Another issue relates to doing PIPE_FREE on a pipe that has a mixer and is running on non-primary core. Fixes are fairly rough with a performance hit to other cases, so some development time is still needed before these can be submitted for review.

**Comment by kv2019i** [comment] 2022-04-08 10:14
Multipe PRs merged to addres sthis bug, but #5628 is still open (and under work).

**Comment by kv2019i** [comment] 2022-04-14 17:09
All patches merged for XTOS builds. For Zephyr builds I still have one patch in the works, but this is harder to hit. Let's monitor test results and close the bug if failure not seen.

**Comment by keqiaozhang** [comment] 2022-04-18 01:54
haven't seen this issue in CI for 10 days, closing this bug.

**Closed by keqiaozhang** 2022-04-18 01:54 UTC
Labels: bug, P2, TGL, xrun, ADL
