### ISSUE TITLE
[BUG][mtl-003] failed to ready HDA controller gctl 0x0 when enabling runtime_PM on MTL platforms

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#6938] opened 2023-01-11 13:14 UTC
**Describe the bug**
This issue is similar with https://github.com/thesofproject/linux/issues/4077   (Duplicate)

We observed this issue on all MTL platforms when enabling runtime PM, it's hard to tell how to reproduce the issue, it does not happen when testing a specific case, but it will occur after testing to a certain extent or testing for a while.  When the issue happens, runtime_status displays error:
```
$ cat /sys/bus/pci/devices/0000\:00\:1f.3/power/runtime_status
error
```
The dmesg shows that:
```
[ 2076.722836] kernel: snd_sof:snd_sof_pci_update_bits_unlocked: sof-audio-pci-intel-mtl 0000:00:1f.3: Debug PCIR: 00000000 at  00000044
[ 2076.722973] kernel: snd_sof:snd_sof_pci_update_bits_unlocked: sof-audio-pci-intel-mtl 0000:00:1f.3: Debug PCIR: 00000000 at  00000048
[ 2076.822869] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: failed to ready HDA controller gctl 0x0
[ 2076.822920] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: failed to exit HDA controller reset
[ 2076.822987] kernel: snd_sof:snd_sof_pci_update_bits_unlocked: sof-audio-pci-intel-mtl 0000:00:1f.3: Debug PCIR: 00000000 at  00000048
[ 2076.823032] kernel: snd_sof:snd_sof_pci_update_bits_unlocked: sof-audio-pci-intel-mtl 0000:00:1f.3: Debug PCIW: 00000040 at  00000048
[ 2076.823048] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: failed to start controller after resume
[ 2076.823084] kernel: snd_sof_intel_hda_common:hda_dsp_state_log: sof-audio-pci-intel-mtl 0000:00:1f.3: Current DSP power state: D0I0
[ 2076.823092] kernel: snd_sof:sof_set_fw_state: sof-audio-pci-intel-mtl 0000:00:1f.3: fw_state change: 0 -> 2
[ 2076.823099] kernel: snd_sof:snd_sof_load_firmware: sof-audio-pci-intel-mtl 0000:00:1f.3: loading firmware
[ 2076.823104] kernel: snd_sof:sof_set_fw_state: sof-audio-pci-intel-mtl 0000:00:1f.3: fw_state change: 2 -> 3
[ 2076.874430] kernel: snd_sof_intel_hda_common:mtl_dsp_pre_fw_run: sof-audio-pci-intel-mtl 0000:00:1f.3: FW Poll Status: reg[0x1000]=0x0 timedout
[ 2076.874463] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: failed to enable DSP subsystem
[ 2076.874530] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: failed pre fw run op
[ 2076.874579] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: failed to boot DSP firmware after resume -110
[ 2076.874648] kernel: snd_sof:sof_set_fw_state: sof-audio-pci-intel-mtl 0000:00:1f.3: fw_state change: 3 -> 4
[ 2076.874684] kernel: soundwire_intel soundwire_intel.link.0: ASoC: error at snd_soc_pcm_component_pm_runtime_get on soundwire_intel.link.0: -16
[ 2076.874774] kernel:  SDW0-Capture: ASoC: error at __soc_pcm_open on SDW0-Capture: -16
[ 2076.874901] kernel:  Jack in: ASoC: error at dpcm_be_dai_startup on Jack in: -16
[ 2076.874976] kernel:  Jack in: ASoC: error at dpcm_fe_dai_startup on Jack in: -16
```

**To Reproduce**
```
1. aplay   -Dhw:0,31 -r 48000 -c 2 -f S16_LE -d 100 /dev/zero -v -q 
2. sleep 5
3. arecord   -Dhw:0,1 -r 48000 -c 2 -f S16_LE -d 5 /dev/null -v -q 
```

**Reproduction Rate**
Hard to tell ATM. But the reproduction rate is high.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: [f1f7c4f4c678](https://github.com/thesofproject/linux/commit/f1f7c4f4c678)
    * SOF: mtl-003-drop-stable
2) Name of the platform(s) on which the bug is observed.
    * Platform: MTL-HDA, MTL-NOCODEC and MTL-SDW

**Comment by plbossart** [comment] 2023-01-11 16:22
@keqiaozhang Does this PR help https://github.com/thesofproject/linux/pull/4082

Looks like the same error to me.

**Comment by keqiaozhang** [comment] 2023-01-12 07:58
I have figured out a easy way to reproduced the issue:
```
1. aplay   -Dhw:0,31 -r 48000 -c 2 -f S16_LE -d 100 /dev/zero -v -q 
2. sleep 5
3. arecord   -Dhw:0,1 -r 48000 -c 2 -f S16_LE -d 5 /dev/null -v -q 
```
Then you will run to the issue, the reproduction rate is almost 100%. Please do not decrease the duration(-d 100) when running aplay on Deepbuffer pipeline 0,31. I tried to decrease the duration to 5s or 10s, but it's very hard to reproduce the issue.

**Comment by keqiaozhang** [comment] 2023-01-12 08:48
> @keqiaozhang Does this PR help [thesofproject/linux#4082](https://github.com/thesofproject/linux/pull/4082)

wow, PR https://github.com/thesofproject/linux/pull/4082 can fix the issue. No reproductions after applying the PR(20+ iterations passed).

BTW, this PR also can fix issue [#4077](https://github.com/thesofproject/linux/issues/4077)

**Comment by plbossart** [comment] 2023-01-13 16:33
> I have figured out a easy way to reproduce the issue:
> 
> ```
> 1. aplay   -Dhw:0,31 -r 48000 -c 2 -f S16_LE -d 100 /dev/zero -v -q 
> 2. sleep 5
> 3. arecord   -Dhw:0,1 -r 48000 -c 2 -f S16_LE -d 5 /dev/null -v -q 
> ```
> 
> Then you will run to the issue, the reproduction rate is almost 100%. Please do not decrease the duration(-d 100) when running aplay on Deepbuffer pipeline 0,31. I tried to decrease the duration to 5s or 10s, but it's very hard to reproduce the issue.

Wondering what the long playback could possibly cause. The only thing I can think of is some sort of power transition done by the PMC of something. Can we try to disable DMI_L1 to see if this plays any role?

 @ranj063 @kv2019i any other ideas?

**Comment by ranj063** [comment] 2023-01-13 16:38
> Wondering what the long playback could possibly cause. The only thing I can think of is some sort of power transition done by the PMC of something. Can we try to disable DMI_L1 to see if this plays any role?

@plbossart with the deep buffer playback, we do put the DSP into D0i3 only after 5s of playback. So it makes sense that a shorter test doesnt reproduce the problem but a longer test does. @keqiaozhang if you have the dmesg log when the issue happens, can you see what the DSP state after your stop the first aplay and runtime PM kicks in?

**Comment by plbossart** [comment] 2023-01-13 16:51
HA! very interesting @ranj063, and it could be very well be that the deep buffer causes additional transitions at the PMC level since there are fewer DMA transfers. How can we disable D0i3?

**Comment by ranj063** [comment] 2023-01-13 16:53
> HA! very interesting @ranj063, and it could be very well be that the deep buffer causes additional transitions at the PMC level since there are fewer DMA transfers. How can we disable D0i3?

simplest way is to remove the D0i3_COMPATIBLE flag in topology.

**Comment by plbossart** [comment] 2023-01-13 17:56
> > HA! very interesting @ranj063, and it could be very well be that the deep buffer causes additional transitions at the PMC level since there are fewer DMA transfers. How can we disable D0i3?
> 
> simplest way is to remove the D0i3_COMPATIBLE flag in topology.

we should have a kernel parameter for this, that would be ideal.

**Comment by RanderWang** [comment] 2023-01-18 06:39
> > Wondering what the long playback could possibly cause. The only thing I can think of is some sort of power transition done by the PMC of something. Can we try to disable DMI_L1 to see if this plays any role?
> 
> @plbossart with the deep buffer playback, we do put the DSP into D0i3 only after 5s of playback. So it makes sense that a shorter test doesnt reproduce the problem but a longer test does. @keqiaozhang if you have the dmesg log when the issue happens, can you see what the DSP state after your stop the first aplay and runtime PM kicks in?

I can confirm that DSP is in D0i0 when runtime PM kicks in. The steps are:
(1)	Use deep buffer to do playback. Kernel driver set d0i3 register in HDA memory space and send ipc msg to fw
(2)	Stop deep buffer stream, exit d0i3 state to d0i0 ( clear d0i3 also send ipc msg to fw)
(3)	Audio system enter d3 state
(4)	Audio system exit d3 state and enter d0 state, reset HDA link.  Get error when exiting HDA link reset state.

 This issue is related to PMC since PMC driver for mtl is not merged in current Linux repo.  If we don't set d0i3c register in host no issue happen, so we will discuss with hw expert about d0i3c setting

**Comment by wszypelt** [comment] 2023-02-03 09:30
Issue should be verified after close: https://github.com/thesofproject/linux/issues/4077

**Comment by mengdonglin** [comment] 2023-02-09 05:10
Cannot reproduce after fix https://github.com/thesofproject/linux/pull/4173 got merged. Closing.

**Closed by mengdonglin** 2023-02-09 05:10 UTC
Labels: bug, duplicate, P1, HDA, I2S, SDW, MTL, mtl-003
