### ISSUE TITLE
Playback is silent on WHL RVP

### ISSUE THREAD

**Issue by DarrenxWang** [thesofproject/sof#671] opened 2018-12-05 09:44 UTC
Summary:
Playback by headset is silent on WHL RVP

dmesg:
no error

Test steps:
aplay -D hw:0,0 -r 48000 -c 2 -f s16_le Music/California_Dreaming_48k_24bit.wav -vv

Expected result:
Sound can be heard from the headset during playback.

Actual result:
The headset is silent.

Test env:
sof master: 12e11b76
kernel sof-dev: d0fbf1c6
tplg: sof-hda-generic.tplg.tplg-12e11b76

Log:
[dmesg.log](https://github.com/thesofproject/sof/files/2648157/dmesg.log)
[logger.txt](https://github.com/thesofproject/sof/files/2648158/logger.txt)

**Comment by lgirdwood** [comment] 2018-12-05 10:29
@DarrenxWang what output are you expecting audio from and what are the alsamixer settings ? ASLA setting can be dumped to text file and attached using "alsactl store -f filename"

**Comment by mengdonglin** [comment] 2018-12-05 15:10
@lgirdwood This error is not caused by amixer setting.  @RanderWang confirmed that this regression is caused by he revised the DAI format from 32 bit to 24 bit, and need further debugging on firmware side. He found both playback and capture by ALC700 is silent now.

**Comment by mengdonglin** [comment] 2018-12-05 15:11
@DarrenxWang However, please help to share the amixer settings. It will be helpful to involve firmware engineers for further debugging.

**Comment by zhuyingjiang** [comment] 2018-12-07 06:34
The result is 16bit and 32bit can play, but with noise, 24bit is silent. Capture can't work. I will debug on this.

**Comment by mengdonglin** [comment] 2018-12-11 13:31
@RanderWang @zhuyingjiang So this issue is blocked or actually a duplicate of #700, right?

**Comment by jajanusz** [comment] 2018-12-11 13:35
@mengdonglin 
I think you can close this issue because it's too broad, only 24b is bugged and #700 address it better.

**Comment by zhuyingjiang** [comment] 2018-12-11 13:46
Yes, this can be closed, since 16/32 playback and capture works.

**Comment by zhuyingjiang** [comment] 2018-12-12 05:59
linux version :https://github.com/thesofproject/linux: 4052ad89a474a84b2b

kconfig : https://github.com/thesofproject/kconfig : 1c7649a29db5b1930cc
make defconfig; 
scripts/kconfig/merge_config.sh .config <PATH>/kconfig/base-defconfig <PATH>/kconfig/sof-defconfig <PATH>/kconfig/hdaudio-codecs-defconfig
make menuconfig  un-select HDA audio PCI

sof version: https://github.com/thesofproject/sof : 12e11b7693f04c1658b7e
build sof-cnl.ri

tplg: change tools/topology/sof-hda-generic.m4 s24le to s16le when build 16bit tplg, change to s32le when build 32bit tplg
Result: 16 bit /32 bit playback capture and HDMI DP are all OK. 24bit remain silent

**Closed by zhuyingjiang** 2018-12-12 05:59 UTC
Labels: P1, WHL, bug, duplicate
