### ISSUE TITLE
Stress test: ipc error when playback and capture(through DMIC) at the same time.

### ISSUE THREAD

**Issue by SinianYang** [thesofproject/sof#187] opened 2018-08-02 10:19 UTC
This issue happens when running playback and capture at same time and run capture through dmic. 
but we can rerun aplay and arecord after ipc error happened. 

The reproducibility is almost 100%.
How to reproduce:
    1.start playback and capture at same time
       aplay -D hw:0,5 -c 2 -r 48000 -f s16_le /dev/zero -d 3 & arecord -D hw:0,6 c 4 -r 48000 -f s32_le 
       /dev/null -vv -i -d 3
     2.repeat step 1.

Environment:
on UP^2
sof-dev: 08f7ddbcdd7eb4fcbf43cef09272215ef53dba7c
sof: af84ef2c6374482177d9153f1f2315a89d32032b
soft: cfff9e0b0402f0f7dd2bd9ba915fd6d1599b2fc8
tplg file name:  sof-apl-nocodec.tplg
log:
[dmesg.log](https://github.com/thesofproject/sof/files/2253006/dmesg.log)
[memorywindow.log](https://github.com/thesofproject/sof/files/2253007/memorywindow.log)
[rmbox.log](https://github.com/thesofproject/sof/files/2253012/rmbox.log)

**Comment by keqiaozhang** [comment] 2018-08-17 07:52
Close this bug, we cannot reproduce this issue with 2ch DMIC and topology doesn't support 4ch so far. we will test with 4ch after this feature is enabled in tplg.

**Closed by keqiaozhang** 2018-08-17 07:52 UTC
Labels: APL, bug
