### ISSUE TITLE
[BUG][BYT-NOCODEC]Input/output error  when aplay via (0,1) using format s24_le/s32_le

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/sof#3171] opened 2020-07-13 10:54 UTC
**Describe the bug**
Input/output error  when aplay via (0,1) using format s24_le/s32_le
After error occured all the pipeline can work

**To Reproduce**
1."sudo reboot" to reboot system
2.cd sof-test
3.cd test-case
4.export TPLG=sof-byt-nocodec.tplg 
5.check-playback.sh -d 3 -l 1 -r 1 -F

**Reproduction Rate**
10/10

**Expected behavior**
No error occured

**Impact**
Input/output error  when aplay via (0,1) using format s24_le/s32_le

<img width="495" alt="Capture" src="https://user-images.githubusercontent.com/56707932/87296963-3d926200-c53a-11ea-8b3b-d7aa3fa898f4.PNG">

```
ubuntu@jf-byt-mb-nocodec-1:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofnocodec [sof-nocodec], device 0: PCM (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofnocodec [sof-nocodec], device 1: PCM Deep Buffer (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0


ubuntu@jf-byt-mb-nocodec-1:~$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: sofnocodec [sof-nocodec], device 0: PCM (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
No error dmesg,no error sof error trace

**Environment**
Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
Kernel: {sof-dev fa7850de}
SOF: {master:318dc9f7}
Name of the topology file
Topology: {sof-byt-nocodec.tplg }
Name of the platform(s) on which the bug is observed.
Platform: {BYT MB with nocodec}
[sof-logger_0713.log](https://github.com/thesofproject/sof/files/4911968/sof-logger_0713.log)

[dmesg_0713.log](https://github.com/thesofproject/sof/files/4911967/dmesg_0713.log)

**Comment by Liviali155** [comment] 2020-07-13 10:58
BYT_MB_RT5682 also has this issue

**Comment by mengdonglin** [comment] 2020-07-14 08:01
sof-byt-nocodec.tplg is created from "sof-cht-nocodec.m4", updated in https://github.com/thesofproject/sof/pull/3080 to remove SRC for Baytrail and CherryTrail by @plbossart

**Comment by lgirdwood** [comment] 2020-07-14 15:38
@Liviali155 as @mengdonglin says lets reduce the BYT/CHT tests to reflect the new topologies.

**Comment by plbossart** [comment] 2020-07-14 15:45
we use the same pipe type of the two PCM devices, so not sure why one would support a format and not the other. This looks like a fundamental bug or a topology edit issue.

**Comment by plbossart** [comment] 2020-07-29 00:00
Can you retry with SOF PR #https://github.com/thesofproject/sof/pull/3245
Thanks!

**Comment by Liviali155** [comment] 2020-07-29 03:09
After applied #3245,issue still can be reproduced on BYT MB with nocodec
<img width="694" alt="Capture" src="https://user-images.githubusercontent.com/56707932/88752196-e2907a00-d18b-11ea-9c74-cd329d27ce20.PNG">
[0729dmesg.log](https://github.com/thesofproject/sof/files/4992291/0729dmesg.log)
[sof-logger0729.log](https://github.com/thesofproject/sof/files/4992293/sof-logger0729.log)

**Comment by plbossart** [comment] 2020-07-29 20:09
@Liviali155 work-around suggested with https://github.com/thesofproject/sof/pull/3257

Can you double-check the results? Also shouldn't this test be part of CI? It's been reporting no issues on this.

**Comment by Liviali155** [comment] 2020-07-30 05:51
Tried with #3257,error not seen

**Comment by slawblauciak** [comment] 2020-08-10 12:50
@Liviali155 that change has been merged, good to close now?

**Comment by plbossart** [comment] 2020-08-10 13:50
> @Liviali155 that change has been merged, good to close now?

I'd like to keep it for now, there's no rational explanation as to why reducing the period size solves the problem. I think we have more fundamental problem with scheduling.

**Comment by slawblauciak** [comment] 2020-09-15 07:37
@mengdonglin please assign it to somebody who maintains legacy platforms.

**Comment by keqiaozhang** [comment] 2020-09-15 08:18
Confirmed that this issue is not reproducible for a long time.

**Comment by mengdonglin** [comment] 2020-09-15 08:30
@plbossart @keqiaozhang Close this issue . We can monitor if this issue will happen again on BYT.

**Closed by mengdonglin** 2020-09-15 08:30 UTC
Labels: BYT, Fix confirmed, P2, bug
