### ISSUE TITLE
White noise when doing 16 bit playback/record via I2S on ICL

### ISSUE THREAD

**Issue by DarrenxWang** [thesofproject/sof#552] opened 2018-11-08 08:10 UTC
Summary:
White noise when doing 16 bit playback/record by I2S on firware branch icl-001-drop-stable. 24 bit/32bit playback/capture works well w/o this issue.

And this issue seems to be a branch-specific firmware issue for icl-001-drop-stable.
Because with the same kernel & topology, this issue cannot be reproduced on firmware master branch (commit 33e4b99351) plus the patch below 0001-DMIC-Enable-power-for-DMIC-for-ICL-platform.patch

Test steps:
aplay -D hw:0,0 Music/48California_Dreaming.wav -d 20   & arecord -Dhw:0,0 -f S16_LE -r 48000 -c 2 test.wav -d 20

Test env:
Sof- icl-001-drop-stable: 40c054ab3087466

Soft-Soft- master: 937032fb5f20 + 1 Patch 
[0001-topology-sample-code-for-icl-topology.patch.txt](https://github.com/thesofproject/sof/files/2560788/0001-topology-sample-code-for-icl-topology.patch.txt)

Linux kernel: topic/sof-dev: af44aa9b + 3 Kernel patches
[0001-ASoC-Intel-hdac_hdmi-add-Icelake-support.patch.txt](https://github.com/thesofproject/sof/files/2560786/0001-ASoC-Intel-hdac_hdmi-add-Icelake-support.patch.txt)
[0002-ASoC-intel-add-icelake-dummy-codec-match-table.patch.txt](https://github.com/thesofproject/sof/files/2560789/0002-ASoC-intel-add-icelake-dummy-codec-match-table.patch.txt)
[0003-ASoC-Intel-add-ICL-machine-driver.patch.txt](https://github.com/thesofproject/sof/files/2560790/0003-ASoC-Intel-add-ICL-machine-driver.patch.txt)

Firmware patch：
[0001-DMIC-Enable-power-for-DMIC-for-ICL-platform.patch.txt](https://github.com/thesofproject/sof/files/2560777/0001-DMIC-Enable-power-for-DMIC-for-ICL-platform.patch.txt)

Log&Wav:
There is no obvious error in kmesg.
[linux_dmesg.log](https://github.com/thesofproject/sof/files/2560863/linux_dmesg.log)
[logger.txt](https://github.com/thesofproject/sof/files/2560771/logger.txt)
[wav.zip](https://github.com/thesofproject/sof/files/2560767/wav.zip)

**Comment by mrajwa** [comment] 2018-11-08 11:15
The only significant difference between the commit that is fine 33e4b99 and the icl-001-drop-stable is this commit 4fa9a7b386. @singalsu, could you please check if you see reported noise issue caused by your commit changes?

**Comment by singalsu** [comment] 2018-11-08 16:04
@mrajwa I don't have ICL. Do you know which bits -> bits conversion is the suspected volume controller doing?

**Comment by singalsu** [comment] 2018-11-08 16:41
I made just PR #555. That's an obvious error, sorry for that. If the playback / capture pipelines in  ICL did s24 -> s16 sample format conversion in volume that should impact.

**Comment by DarrenxWang** [comment] 2018-11-09 07:49
There is white noise when doing 16 bit playback/record by I2S. 
There is no white noise when doing 24/32 bit playback/record by I2S.

**Comment by singalsu** [comment] 2018-11-09 09:14
@DarrenxWang I don't have device to test this conversion. Can you please test if PR #555 fixes this.

**Comment by bardliao** [comment] 2018-11-09 09:33
@mrajwa @singalsu This issue is fixed by PR #555 . Thanks

**Comment by singalsu** [comment] 2018-11-09 10:03
@bardliao Excellent, thanks!

**Comment by singalsu** [comment] 2018-11-09 10:30
Closing this issue.

**Closed by singalsu** 2018-11-09 10:30 UTC
Labels: ICL, P1, br-icl, bug, exported
