### ISSUE TITLE
[BUG][MTL][HDA]  A volume drop wave at the beginning of headset recording

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#7116] opened 2023-02-17 02:34 UTC
**Describe the bug**
when checking headset capture with zero data, we observed there's a volume drop wave at the beginning. Not sure if it's a power up pop noise or a real gain issue. Need help from developer to clarify.

![image](https://user-images.githubusercontent.com/22468760/219534387-40742e4a-c636-4c70-bec4-24a7fc134466.png)

![image](https://user-images.githubusercontent.com/22468760/219534210-f7c20cd4-4a20-48e9-a697-2305e9d28701.png)

**To Reproduce**
arecord -Dhw:0,0 -f dat -c 2 test.wav -vvv

**Reproduction Rate**
100%

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * SOF: main branch
2) Name of the topology file
    * Topology: sof-hda-generic-4ch.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: MTLP-RVP-HDA with Realtek AIOC31 + Transducer board

**Comment by lgirdwood** [comment] 2023-02-20 10:53
@singalsu @andrula-song any comments ?

**Comment by singalsu** [comment] 2023-02-20 12:33
It's a DC level settling in headset microphone. Should add the high-pass IIR to headset capture pipeline, 0 dB gain 40 Hz cut-off as we have in tplg1 in sof-hda-generic. I'm working on adding it to DMIC and I can address this too.

**Comment by singalsu** [comment] 2023-02-20 14:04
@keqiaozhang Can you please try #7128 if it helps.

**Comment by keqiaozhang** [comment] 2023-02-22 08:07
> Can you please try #7128 if it helps.

Verified on MTL-HDA, no volume drop at the beginning of recording after applying https://github.com/thesofproject/sof/pull/7128
![image](https://user-images.githubusercontent.com/22468760/220559814-ccf8c61e-6c3d-4478-9178-4efc9472cc7d.png)

**Comment by andrula-song** [comment] 2023-02-22 08:22
Thanks Seppo! But in fact, this should be something like the noise of hardware codec power-on, we do can use IIR to filter it out, but can we ask hardware experts to help solve him from the root cause?

**Comment by singalsu** [comment] 2023-02-22 09:26
@andrula-song The reason for the DC in the beginning is the settling of the single ended microphone bias circuit. It would be avoided with a differential microphone connection but there's not enough pins for such in four pole 3.5 mm stereo plug (gnd, mic, l, r). There's a DC level jump always when the mic BIAS is enabled or when headset button is pressed (pulls down the mic line).

If a codec has a similar digital high-pass filter that could be enabled it would fix this similarly. I don't know if such exists but at least such does not seem to be enabled by Linux drivers. I don't see such ALSA control in alsamixer of e.g. ALC888.

This also improves sound quality of headset in wind outdoors and such so finding out codec's capability to do this would be good. 

Meanwhile the fix should be merged since we have the same fix in tplg1 for all hda-generic platforms. It's easy to remove the filter from topology if codec gets the same feature.

**Closed** 2023-03-02 22:55 UTC
Labels: bug, HDA, MTL
