### ISSUE TITLE
"DSP panic" during capture, do the pause/release, the firmware enter panic.

### ISSUE THREAD

**Issue by ghost** [thesofproject/sof#168] opened 2018-07-30 09:26 UTC
platform info:
on the apl platform.

code version info:
sof: master:  commit-id: 4157d939b75d13aacd1d5c70b37a141890892ef4
linux: topic/sof-dev: commit-id: 46b7b641555171efd7834f41f666bb47f12d05b0
tool: master: commit-id: debaf8f889607406159a13f8bba7d7218243683d

reproduce steps:
1. do the capture operation.
2. pause / release the capture.
3. the issue will be reproduced.

[rmbox-error.txt](https://github.com/thesofproject/sof/files/2240461/rmbox-error.txt)
[dmesg.txt](https://github.com/thesofproject/sof/files/2240462/dmesg.txt)

**Comment by zhigang-wu** [comment] 2018-07-30 09:33
bisect the patch "8c23b24".

**Comment by keqiaozhang** [comment] 2018-07-30 10:45
This issue is related to the compiler, confirmed that this issue only happens with gcc compiler and cannot reproduce this issue with xcc.

**Comment by lgirdwood** [comment] 2018-07-30 11:08
@keqiaozhang can you paste the disassembly of the functions that EPC1 and EPC5 are pointing to. Thanks

**Comment by keqiaozhang** [comment] 2018-07-30 13:40
@lgirdwood 
EPC1     0xbe01c264
be01c264:       106452                  s32i    a5, a4, 64

EPC5     0xbe01c261
be01c261:       40c422                  addi    a2, a4, 64

sof-apl.lst is attached and renamed as sof-apl.txt
[sof-apl.txt](https://github.com/thesofproject/sof/files/2241322/sof-apl.txt)

**Comment by zhigang-wu** [comment] 2018-07-31 01:52
I do not think the PR 8c23b24 is right.

when the capture works, it looks like that,  at the start point.
1. the DAI's DMA is first to start, this means the DAI-DMA's HW pointer is updated first.
2. when one period data is received, the cb() function is entered, the buffer pointer will be updated.
At this time, the DAI-DMA's HW pointer and buffer pointer are matched.

when the pause command comes:
1. the DAI's DMA will finish the current job, the DAI-DMA's HW pointer is updated.
2. when the current job is finished, the cb() function should be entered. the buffer pointer will be updated.
3. but this PR will stop the buffer pointer's update.
the DAI-DMA's HW pointer are mismatch with the buffer pointer now.

when the release command comes:
1. the capture pipeline and DAI DMA are started almost at the same time.
2. the DAI-DMA will continue to work, but buffer pointer is still mismatch.
3. the pipeline will not help this mismatch, because the buffer pointer is updated in the pipeline.

the XRUN will happen.

**Comment by xiulipan** [comment] 2018-07-31 03:16
8c23b24 should be 58bc284905ee8203c17e7d62e4e57bb0bf4dd2b4

> 
>     dai: ignore data on capture stop
> 
>     Ignores data on stopping capture stream.
> 
>     Signed-off-by: Tomasz Lauda <tomasz.lauda@linux.intel.com>

**Comment by tlauda** [comment] 2018-07-31 06:14
@zhigang-wu @xiulipan This is actually a nice catch, but it also means, that we have the wrong approach to the stop sequence implementation. Until now I have assumed, that after stop - start we should continue from the previous pipeline state, but it seems that we should just drop everything and start from the beginning. I think we should revert 58bc284905ee8203c17e7d62e4e57bb0bf4dd2b4 and play around with pipeline_prepare() before start. Have you guys confirmed, that doing prepare before the start fixes the noise issue?

**Comment by zhigang-wu** [comment] 2018-07-31 08:58
this issue can be fixed by the revert PR #176

**Comment by zhuqingliang** [comment] 2018-07-31 11:19
also reproduced on CNL with  5e83da7fc170dd9eccdf97e32a516a5b294a41bf

**Closed as completed** 2018-08-02 02:57 UTC
Labels: APL
