### ISSUE TITLE
Volume component signal overflow with extreme levels

### ISSUE THREAD

**Issue by juimonen** [thesofproject/sof#416] opened 2018-09-26 07:21 UTC
There's mild crackling noise coming from volume component if volume levels are at maximum and incoming signal has very high levels (has to peak at max sample values). This is very "pathological" use case but might actually happen, I was getting this with pcm ripped from CD and running through sox conversion to 48kHz (which clipped couple of very high level samples). Also able to get it with a sine sweep maxed to 0dB.  From recorded pcm you can see that there are couple of very sharp transitions from positive to negative -> overflow.

**Comment by mengdonglin** [comment] 2018-09-30 02:33
@juimonen Could you add the labels for the platform and branch on which you observe the bug? Thanks!

**Comment by juimonen** [comment] 2018-09-30 08:17
I saw this with up2 and master branch. However I think this will manifest in all configurations, but I have not tested all of them. It could be a certain "version" of the volume processing function (like some 24 bit to 32 bit) but I could not find/fix it yet because trace went berserk...

**Comment by lgirdwood** [comment] 2018-10-01 15:12
@singalsu any thoughts on this one ?

**Comment by singalsu** [comment] 2018-10-01 15:54
Yes, I've heard this noise too. There's rattle with highest volume and it goes away with next lower step. The volume mode in the test pipeline is 32->24. I need to test if there's difference in gcc and/or xt-xcc compiled volume since they use a different gain algo core. We can debug this now when we got trace to work again.

**Comment by singalsu** [comment] 2018-11-01 15:39
I'll start working with debugging this. I was just able to reproduce it and confirmed that this happens with gcc build and 32->24 volume mode. It doesn't happen with 16->24 and 24->24.

**Comment by singalsu** [comment] 2018-11-02 10:59
Confirmed the bug and made a fix, PR to appear soon. I need to review other conversions for similar issue. The q_multsr_sat_32x32() function ensures proper saturation to 32 bits but if the output of volume is 24 bits the result may be still be an overflow. Need to instead calculate 32 bit result and shift right by 8 to get a properly saturated 24 bit sample.

![snd_volume_rattle](https://user-images.githubusercontent.com/28754793/47911744-f0be4300-de9e-11e8-9185-2fe3441a4505.png)

**Comment by mengdonglin** [comment] 2018-11-19 01:34
@juimonen Could you help to check if this issue is fixed by PR #528 on your side? If yes, please help to close the issue. Thanks!

**Closed as completed** 2018-11-19 08:24 UTC
Labels: bug, APL, P2
