### ISSUE TITLE
[BUG][JSL] Failed to load firmware on JSL

### ISSUE THREAD

**Issue by yangxiaohua2009** [thesofproject/sof#4916] opened 2021-10-26 01:11 UTC
**Describe the bug**
The sof DSP failed to boot and the dmesg shows FW Poll Status: reg[0x80000]=0x80000012 timedout on JSL.
The problem looks like #2888 but the error code is different.

**To Reproduce**
Select to use sof on JSL.

**Reproduction Rate**
10/10

**Expected behavior**
DSP firmware boots normally and the start-up process goes on.

**Impact**
firmware boot failure.

**Environment**
1) Kernel: 5.14.7
2) SOF: 1:9:0-fa857
3) Platform: JSL

**Screenshots or console output**
[    6.833291] sof-audio-pci-intel-icl 0000:00:1f.3: FW Poll Status: reg[0x80000]=0x80000012 timedout
[    6.833296] sof-audio-pci-intel-icl 0000:00:1f.3: error: cl_copy_fw: timeout HDA_DSP_SRAM_REG_ROM_STATUS read
[    6.833824] sof-audio-pci-intel-icl 0000:00:1f.3: FW Poll Status: reg[0x160]=0x140000 successful
[    6.833866] sof-audio-pci-intel-icl 0000:00:1f.3: unknown ROM status value 80000012
[    6.833888] sof-audio-pci-intel-icl 0000:00:1f.3: error: extended rom status:  0x80000012 0x2c 0x0 0x0 0x0 0x0 0x2100186 0x0
[    6.833890] sof-audio-pci-intel-icl 0000:00:1f.3: error: load fw failed ret: -110
[    6.833917] sof-audio-pci-intel-icl 0000:00:1f.3: error: failed to reset DSP
[    6.833919] sof-audio-pci-intel-icl 0000:00:1f.3: error: failed to boot DSP firmware -110
[    6.884371] sof-audio-pci-intel-icl 0000:00:1f.3: FW Poll Status: reg[0x4]=0x1d003c timedout
[    6.884375] sof-audio-pci-intel-icl 0000:00:1f.3: error: hda_dsp_core_reset_enter: timeout on HDA_DSP_REG_ADSPCS read
[    6.884378] sof-audio-pci-intel-icl 0000:00:1f.3: error: dsp core reset failed: core_mask 1
[    6.884658] sof-audio-pci-intel-icl 0000:00:1f.3: error: sof_probe_work failed err: -110

[dmesg2.log](https://github.com/thesofproject/sof/files/7408426/dmesg2.log)

**Comment by plbossart** [comment] 2021-11-05 20:11
@lgirdwood @mwasko this problem was reproduced by @hli25, it would appear the firmware was signed either with the wrong key, wrong masks or wrong CSE tools.

**Comment by mwasko** [comment] 2021-11-08 16:53
@plbossart the JSL 1.9 FW signature looks ok, but I will take a closer look on that

**Comment by plbossart** [comment] 2021-11-10 17:07
@yangxiaohua2009 @tomty89 @systematicat can you unzip this file 
[sof-jsl-signed.ri.gz](https://github.com/thesofproject/sof/files/7514615/sof-jsl-signed.ri.gz) as /lib/firmware/intel/sof/sof-jsl.ri and retry? Internal tests show that this solves the authentication problem. This file would be added to the 1.9.2 release if it's successful. Thanks!

**Comment by lgirdwood** [comment] 2021-11-12 17:49
@marc-hb fyi - will need a release update.

**Comment by marc-hb** [comment] 2021-11-12 18:14
> it would appear the firmware was signed either with the wrong key, 

Indeed it looks like JSL was signed with the ICL key:

```
for i in ./sof-bin/v1.9.x/sof-v1.9/intel-signed/sof-*.ri; do
  echo "$i"; ./sof/tools/sof_ri_info/sof_ri_info.py -v "$i" | grep -i key
done

sof-bin/v1.9.x/sof-v1.9/intel-signed/sof-glk.ri
        1f f4 58 74 64 d4 ae 90 ... b5 c2 49 4e 2a 5f 47 c2 (APL Intel prod key)
sof-bin/v1.9.x/sof-v1.9/intel-signed/sof-icl.ri
        63 df 54 e3 c1 e5 d9 d2 ... 35 f1 ec 4d 93 73 e6 c4 (ICL Intel prod key)
sof-bin/v1.9.x/sof-v1.9/intel-signed/sof-jsl.ri
        63 df 54 e3 c1 e5 d9 d2 ... 35 f1 ec 4d 93 73 e6 c4 (ICL Intel prod key)
sof-bin/v1.9.x/sof-v1.9/intel-signed/sof-tgl-h.ri
        d3 72 92 99 4e b9 cd 67 ... 5d 62 4a 80 96 31 f8 b5 (TGL Intel prod key)
```

**Comment by tomty89** [comment] 2021-11-13 14:17
@plbossart Yeah the errors are gone with the firmware you linked.

However, I can't actually get proper sound out of my laptop when I have kernel 5.15.2 patched in the way I mentioned in https://github.com/thesofproject/linux/issues/3210#issuecomment-943506955. All I get is a "pop" when the device is opened (when on headphone) and closed. (But well, I suppose I'll won't actually use the internal card anyway unless a driver from the codec vendor is mainlined...)

**Comment by plbossart** [comment] 2021-11-15 18:19
@tomty89 thanks for testing, much appreciated.

 the latest code we have to support Intel platforms with the ES83316 device is here: https://github.com/thesofproject/linux/pull/3107
You would need to pick this branch and install a custom kernel.

If you can give it a try and report your findings in https://github.com/thesofproject/linux/issues/2955 that would be great.

**Comment by tomty89** [comment] 2021-11-15 22:40
@plbossart I already did (please see the linked comment above to see what exactly I've applied), and the result is above -- I get an analog alsa device, but no sound actually coming out (other than the pops mentioned).

**Comment by plbossart** [comment] 2021-11-15 23:08
> @plbossart I already did (please see the linked comment above to see what exactly I've applied), and the result is above -- I get an analog alsa device, but no sound actually coming out (other than the pops mentioned).

@hli25 did you get audible sound on the JSL platform you tested, if yes can you share the alsamixer settings used?

**Comment by hli25** [comment] 2021-11-17 01:03
> > @plbossart I already did (please see the linked comment above to see what exactly I've applied), and the result is above -- I get an analog alsa device, but no sound actually coming out (other than the pops mentioned).
> 
> @hli25 did you get audible sound on the JSL platform you tested, if yes can you share the alsamixer settings used?

Please try to set "DAC" to 100 via alsamixser  @tomty89

**Comment by tomty89** [comment] 2021-11-17 11:23
Nope, it doesn't help (it's 100 by default anyway). And toggling/adjusting other mixer controls doesn't seem to help either. (Btw I don't know if it's expected but there's no master control. There are only the Headphone and Speaker switches and the Headphone Mixer volume control (and a bunch of other whatsoever).

**Comment by lgirdwood** [comment] 2021-11-17 14:08
@tomty89 can you run ```amixer contents``` during playback and past the output here, it could be we are missing one mixer control setting.

**Comment by tomty89** [comment] 2021-11-19 01:11
[amixer_controls.txt](https://github.com/thesofproject/sof/files/7567041/amixer_controls.txt)
[amixer_contents.txt](https://github.com/thesofproject/sof/files/7567046/amixer_contents.txt)

I'm not sure if that could be the cause though. It feels more like some kind of routing / pin problem to me somehow, or some low-level parameters to open the DAC is wrong. Also, after a second thought, the mixer control `DAC` is the `Master`-equivalence.

**Comment by marc-hb** [comment] 2021-11-19 01:31
Please file a different bug for problems happening _after_ loading the firmware.

**Comment by marc-hb** [comment] 2021-11-19 18:03
v1.9.2 has been merged in sof-bin.git

```
/sof/tools/sof_ri_info/sof_ri_info.py -v sof-bin/v1.9.x/sof-v1.9.2/intel-signed/sof-jsl.ri | grep -A1 Modulus
./sof-bin/v1.9.x/sof-v1.9.2/intel-signed/sof-jsl.ri
      Modulus size (dwords) 64
        6f e4 d5 c9 52 f4 01 c1 ... f8 7c b0 09 09 c2 a3 cc (Other)

```
All older `intel-signed/sof-jsl.ri` files had been signed with the `(ICL Intel prod key)`

**Comment by olidietzel** [comment] 2021-12-06 01:57
Chuwi Hi10 Go, jsl Celeron N4500, KDE Neon unstable with signed Debian 5.16rc3 Kernel

Copied suggested fw https://github.com/thesofproject/linux/files/7341855/sof-jsl-es8336.tplg.gz and https://github.com/thesofproject/sof/files/7514615/sof-jsl-signed.ri.gz into intel/sof fw tree, is loaded, ABI warnings, still no sound device. Any hint what to do next, did i miss something? :)

uname -a

Linux toor-hi10go 5.16.0-rc3-amd64 #1 SMP PREEMPT Debian 5.16~rc3-1~exp1 (2021-11-29) x86_64 x86_64 x86_64 GNU/Linux

dmesg | egrep "snd_|sof-"

[    8.376551] snd_hda_intel 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[    8.923427] sof-audio-pci-intel-icl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[    8.923498] sof-audio-pci-intel-icl 0000:00:1f.3: enabling device (0000 -> 0002)
[    8.923729] sof-audio-pci-intel-icl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[    8.923848] sof-audio-pci-intel-icl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    8.931011] sof-audio-pci-intel-icl 0000:00:1f.3: use msi interrupt mode
[    9.018075] sof-audio-pci-intel-icl 0000:00:1f.3: hda codecs found, mask 4
[    9.057111] sof-audio-pci-intel-icl 0000:00:1f.3: firmware: direct-loading firmware intel/sof/sof-jsl.ri
[    9.057130] sof-audio-pci-intel-icl 0000:00:1f.3: Firmware info: version 1:9:2-e096c
[    9.057132] sof-audio-pci-intel-icl 0000:00:1f.3: Firmware: ABI 3:20:0 Kernel ABI 3:18:0
[    9.057134] sof-audio-pci-intel-icl 0000:00:1f.3: warn: FW ABI is more recent than kernel
[    9.057142] sof-audio-pci-intel-icl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
[    9.168476] sof-audio-pci-intel-icl 0000:00:1f.3: Firmware info: version 1:9:2-e096c
[    9.168484] sof-audio-pci-intel-icl 0000:00:1f.3: Firmware: ABI 3:20:0 Kernel ABI 3:18:0
[    9.168487] sof-audio-pci-intel-icl 0000:00:1f.3: warn: FW ABI is more recent than kernel

lsmod | grep snd_

snd_soc_dmic           16384  0
snd_hda_codec_hdmi     73728  0
snd_sof_pci_intel_icl    16384  0
snd_sof_intel_hda_common   106496  1 snd_sof_pci_intel_icl
soundwire_intel        45056  1 snd_sof_intel_hda_common
snd_sof_intel_hda      20480  1 snd_sof_intel_hda_common
snd_sof_pci            20480  2 snd_sof_pci_intel_icl,snd_sof_intel_hda_common
snd_sof_xtensa_dsp     16384  1 snd_sof_intel_hda_common
snd_sof               159744  2 snd_sof_pci,snd_sof_intel_hda_common
snd_soc_hdac_hda       24576  1 snd_sof_intel_hda_common
snd_hda_ext_core       36864  3 snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_sof_intel_hda
snd_soc_acpi_intel_match    61440  2 snd_sof_pci_intel_icl,snd_sof_intel_hda_common
snd_soc_acpi           16384  2 snd_soc_acpi_intel_match,snd_sof_intel_hda_common
ledtrig_audio          16384  1 snd_sof
snd_soc_es8316         53248  0
snd_hda_intel          57344  0
snd_intel_dspcfg       28672  2 snd_hda_intel,snd_sof_intel_hda_common
snd_soc_core          327680  6 soundwire_intel,snd_sof,snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_soc_es8316,snd_soc_dmic
snd_intel_sdw_acpi     20480  2 snd_sof_intel_hda_common,snd_intel_dspcfg
snd_compress           28672  1 snd_soc_core
snd_hda_codec         176128  3 snd_hda_codec_hdmi,snd_hda_intel,snd_soc_hdac_hda
snd_hda_core          110592  7 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_ext_core,snd_hda_codec,snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_sof_intel_hda
snd_hwdep              16384  1 snd_hda_codec
snd_seq_midi           20480  0
snd_seq_midi_event     16384  1 snd_seq_midi
snd_rawmidi            45056  1 snd_seq_midi
snd_pcm               147456  10 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,soundwire_intel,snd_sof,snd_sof_intel_hda_common,snd_compress,snd_soc_core,snd_soc_es8316,snd_hda_core
snd_seq                86016  2 snd_seq_midi,snd_seq_midi_event
snd_seq_device         16384  3 snd_seq,snd_seq_midi,snd_rawmidi
snd_timer              45056  2 snd_seq,snd_pcm
snd                   110592  12 snd_seq,snd_seq_device,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_sof,snd_timer,snd_compress,snd_soc_core,snd_pcm,snd_rawmidi

cat /proc/asound/cards 

--- no soundcards ---

aplay -l
aplay: device_list:276: no soundcards found...

**Closed** 2021-12-06 02:47 UTC
Labels: bug, P1, JSL, Signing, chrome

**Comment by plbossart** [comment] 2021-12-06 15:05
> Chuwi Hi10 Go, jsl Celeron N4500, KDE Neon unstable with signed Debian 5.16rc3 Kernel

try https://github.com/thesofproject/linux/pull/3107 and file a separate issue if this doesn't work for you.
