### ISSUE TITLE
[BUG] FW reported error: 6 - Unknown error while processing the request when disabling a secondary core

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#8588] opened 2023-12-07 09:06 UTC
**Describe the bug**
I did a pre-test on [mtl-007-drop-stable](https://github.com/thesofproject/sof/tree/mtl-007-drop-stable) branch and found this issue when recording for a long time.  The reproduction rate is unclear, I'm doing the manual check now.

**dmesg**
```
[ 5728.131726] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx      : 0x12010000|0x0: GLB_DELETE_PIPELINE
[ 5728.133418] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx reply: 0x32000000|0x0: GLB_DELETE_PIPELINE
[ 5728.133449] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx done : 0x12010000|0x0: GLB_DELETE_PIPELINE
[ 5728.133457] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx      : 0x47000000|0x0: MOD_SET_DX [data size: 8]
[ 5728.535101] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx reply: 0x67000006|0x0: MOD_SET_DX
[ 5728.535114] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: FW reported error: 6 - Unknown error while processing the request
[ 5728.535172] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc error for msg 0x47000000|0x0
[ 5728.535194] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: failed to disable target core: 2 for pipeline pipeline.11
[ 5728.535221] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Failed to free connected widgets
[ 5728.535252] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_hw_free on 0000:00:1f.3: -22
[ 5728.535420] kernel: snd_sof:sof_pcm_close: sof-audio-pci-intel-mtl 0000:00:1f.3: pcm: close stream 2 dir 1
```

**To Reproduce**
~/sof-test/test-case/check-capture.sh -d 500 -l 1 -r 1

**Reproduction Rate**
50%+

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {[266ee31b71f8](https://github.com/thesofproject/linux/commit/266ee31b71f88434f317d78a9ce3e3aec31fdbd8)}
    * SOF: {[mtl-007-drop-stable](https://github.com/thesofproject/sof/tree/mtl-007-drop-stable)
2) Name of the topology file
    * Topology: {development/sof-mtl-nocodec.tplg}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {MTLP_RVP_NOCODEC}

[dmesg.txt](https://github.com/thesofproject/sof/files/13597840/dmesg.txt)
[mtrace.txt](https://github.com/thesofproject/sof/files/13597843/mtrace.txt)

**Comment by keqiaozhang** [comment] 2023-12-07 10:10
This issue can be reproduced manually and the reproduction rate is about 50%+ with stress test case.

**Comment by kv2019i** [comment] 2023-12-08 08:03
The problem seems to relate to multicore scenarios and error in powering down a secondary core. In the original mtrace:

```
[   93.002046] <err> zephyr: cpu_disable_core: core 2 did not enter idle state
[   93.002073] <err> ipc: ipc4_module_process_dx: failed to disable core 2
[   93.002100] <err> ipc: ipc_cmd: ipc4: MODULE_MSG failed with err 6
```

In a more recent case (Intel test plan 35669):
```
[   35.326876] <inf> ipc: ipc_cmd: rx	: 0x47000000|0x0
[   35.726888] <err> zephyr: cpu_disable_core: core 1 did not enter idle state
[   35.726891] <err> ipc: ipc4_module_process_dx: failed to disable core 1
[   35.726895] <err> ipc: ipc_cmd: ipc4: MODULE_MSG failed with err 6Terminated
```

**Comment by keqiaozhang** [comment] 2023-12-08 08:59
Observed this issue on LNL-NOCODEC when testing multiple-pause-resume-50. Inner test ID:35712.

**Comment by mengdonglin** [comment] 2023-12-12 08:46
> @keqiaozhang does the problem also appear on mtl-006?

@wszypelt we didn't observe this issue on mtl-006

**Comment by lgirdwood** [comment] 2023-12-18 16:30
@abonislawski @softwarecki any insights here ? Anything we can check in SW ?

**Comment by keqiaozhang** [comment] 2023-12-20 01:52
This issue also can be reproduced on SOF main branch. Inner test ID:36158.
I also did a check on latest [mtl-007-drop-stable](https://github.com/thesofproject/sof/tree/mtl-007-drop-stable)/6d3061c. The reproduction rate is much lower, but it can still be reproduced with multiple-pipeline related cases.

**Comment by RanderWang** [comment] 2023-12-21 09:00
This is an old bug and can be reproduced two month ago although it is rare.  I debug the issue and found that: the secondary core is in idle status with "waiti 0". Primary core calls  arch_sched_ipi to wake up it but failed.   Idc interrupt is not triggered on secondary core

BTW I did stress test on TGL and didn't found this issue

**Comment by RanderWang** [comment] 2023-12-22 08:08
Do many tests. It should be fixed by https://github.com/thesofproject/sof/pull/8657

**Comment by abonislawski** [comment] 2024-01-03 08:42
I was also debugging this one, main problem is very low reproduction rate, in the end primary core will fail on timeout because secondary core stays in idle didnt enter power-down flow.
In my tests disabling memory retention also lowered reproduction rate
(Sorry, I commented but didnt click Comment before holiday break..)

**Comment by jsarha** [comment] 2024-01-18 09:03
I have hit this a few times on (Onecloud) MTL RVP while debugging #8642. E.g. the bug also happens when running multiple-pipeline test.

**Closed** 2024-03-22 17:39 UTC
Labels: bug, P1, I2S, multicore, MTL, LNL
