### ISSUE TITLE
[BUG][TGL][CI]DSP reset failed on TGLU-VOLT-SDW in check runtime pm status test.

### ISSUE THREAD

**Issue by WYL-12** [thesofproject/sof#3710] opened 2020-12-23 05:35 UTC
Describe the bug
In CI test report 1326, DSP reset failed on TGLU-VOLT-SDW in check runtime pm status test, with below error message:

Error log:
```
aplay: main:830: audio open error: Device or resource busy
2020-12-22 23:15:28 UTC [REMOTE_INFO] runtime status: error
2020-12-22 23:15:28 UTC [REMOTE_ERROR] aplay process for pcm smart373-spk runtime status is not active as expected
2020-12-22 23:15:28 UTC [REMOTE_COMMAND] kill process: kill -9 76984
/home/ubuntu/sof-test/test-case/check-runtime-pm-status.sh: line 122: kill: (76984) - No such process
2020-12-22 23:15:28 UTC [REMOTE_ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
2020-12-22 23:15:28 UTC [REMOTE_ERROR]  main()  @  /home/ubuntu/sof-test/test-case/check-runtime-pm-status.sh
```
Dmesg log:
```
kernel: [ 6403.182926] sof-audio-pci 0000:00:1f.3: error: cl_copy_fw: timeout HDA_DSP_SRAM_REG_ROM_STATUS read
kernel: [ 6403.182936] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x140000 successful
kernel: [ 6403.182947] sof-audio-pci 0000:00:1f.3: unknown ROM status value 05000001
kernel: [ 6403.182957] sof-audio-pci 0000:00:1f.3: error: status = 0x00000000 panic = 0x00000000
kernel: [ 6403.182977] sof-audio-pci 0000:00:1f.3: error: extended rom status:  0x5000001 0x0 0x0 0x0 0x0 0x0 0x25101c2 0x0
kernel: [ 6403.182988] sof-audio-pci 0000:00:1f.3: unknown ROM status value 05000001
kernel: [ 6403.182990] sof-audio-pci 0000:00:1f.3: error: load fw failed ret: -110
kernel: [ 6403.183032] sof-audio-pci 0000:00:1f.3: error: failed to reset DSP
kernel: [ 6403.183036] sof-audio-pci 0000:00:1f.3: error: failed to boot DSP firmware after resume -110
kernel: [ 6403.183047] intel-sdw intel-sdw.1: ASoC: error at snd_soc_pcm_component_pm_runtime_get on intel-sdw.1: -16
kernel: [ 6403.183055]  SDW1-Playback: ASoC: BE open failed -16
kernel: [ 6403.183059]  smart373-spk: ASoC: failed to start some BEs -16
```

To Reproduce
run check runtime pm status test on VOLT.

Reproduction Rate
issue is seen in recent several daily test report.

Environment
Kernel Branch: topic/sof-dev
Kernel Commit: 4cfdde73-1
SOF Branch: master
SOF Commit:eaa9a55d0b84-5

[dmesg.txt](https://github.com/thesofproject/sof/files/5733458/dmesg.txt)

**Comment by aiChaoSONG** [comment] 2020-12-29 04:57
close this, for duplicate of https://github.com/thesofproject/sof/issues/3719

**Closed by aiChaoSONG** 2020-12-29 04:57 UTC
Labels: bug
