### ISSUE TITLE
[BUG]DSP panic and dai_config timeout on APL_UP2_NOCODEC

### ISSUE THREAD

**Issue by XiaoyunWu6666** [thesofproject/sof#4199] opened 2021-05-17 09:26 UTC
**Describe the bug**
DSP panic on APL_UP2_NOCODEC ,causing multiple-pause-resume-25  to fail  since May 13
eg. internal daily 4313,4300
in case 'multiple-pause-resume-25'

**To Reproduce**
Reproduced in CI daily test since May 13)
TPLG=sof-apl-nocodec.tplg ~/sof-test/test-case/multiple-pause-resume.sh -r 25

**Environment**
Kernel Branch: topic/sof-dev
Kernel Commit: caca1987
SOF Branch: main
SOF Commit: 9235eb83608f

**Log**
[console]
```
[  171.902145] kernel: sof-audio-pci-intel-apl 0000:00:0e.0: error : DSP panic!
[  171.902162] kernel: sof-audio-pci-intel-apl 0000:00:0e.0: status: fw entered - code 00000005
[  171.902208] kernel: sof-audio-pci-intel-apl 0000:00:0e.0: error: runtime exception
[  171.902212] kernel: sof-audio-pci-intel-apl 0000:00:0e.0: error: trace point 00004000
[  171.902216] kernel: sof-audio-pci-intel-apl 0000:00:0e.0: error: panic at :0
[  171.902220] kernel: sof-audio-pci-intel-apl 0000:00:0e.0: error: DSP Firmware Oops
[  171.902224] kernel: sof-audio-pci-intel-apl 0000:00:0e.0: error: Exception Cause: LoadStorePIFDataErrorCause, Synchronous PIF data error during LoadStore access
```
[dmesg log]
```
[  171.902145] sof-audio-pci-intel-apl 0000:00:0e.0: error : DSP panic!
[  171.902156] sof-audio-pci-intel-apl 0000:00:0e.0: panic: dsp_oops_offset 788480 offset 788480
[  171.902162] sof-audio-pci-intel-apl 0000:00:0e.0: status: fw entered - code 00000005
[  171.902208] sof-audio-pci-intel-apl 0000:00:0e.0: error: runtime exception
[  171.902212] sof-audio-pci-intel-apl 0000:00:0e.0: error: trace point 00004000
[  171.902216] sof-audio-pci-intel-apl 0000:00:0e.0: error: panic at :0
[  171.902220] sof-audio-pci-intel-apl 0000:00:0e.0: error: DSP Firmware Oops
[  171.902224] sof-audio-pci-intel-apl 0000:00:0e.0: error: Exception Cause: LoadStorePIFDataErrorCause, Synchronous PIF data error during LoadStore access
[  171.902228] sof-audio-pci-intel-apl 0000:00:0e.0: EXCCAUSE 0x0000000d EXCVADDR 0x0000005c PS       0x00060925 SAR     0x00000000
[  171.902233] sof-audio-pci-intel-apl 0000:00:0e.0: EPC1     0xbe0096d3 EPC2     0xbe0091aa EPC3     0x00000000 EPC4    0x00000000
[  171.902238] sof-audio-pci-intel-apl 0000:00:0e.0: EPC5     0x00000000 EPC6     0x00000000 EPC7     0x00000000 DEPC    0x00000000
[  171.902242] sof-audio-pci-intel-apl 0000:00:0e.0: EPS2     0x00060d20 EPS3     0x00000000 EPS4     0x00000000 EPS5    0x00000000
[  171.902247] sof-audio-pci-intel-apl 0000:00:0e.0: EPS6     0x00000000 EPS7     0x00000000 INTENABL 0x00000000 INTERRU 0x00000262
[  171.902251] sof-audio-pci-intel-apl 0000:00:0e.0: stack dump from 0xbe047540
[  171.902257] sof-audio-pci-intel-apl 0000:00:0e.0: 0xbe047540: be047580 be068478 be068478 be04d0e4
[  171.902262] sof-audio-pci-intel-apl 0000:00:0e.0: 0xbe047544: 7e0203bb be0475c0 00000000 00000001
[  171.902267] sof-audio-pci-intel-apl 0000:00:0e.0: 0xbe047548: 3fe76b00 047a3d6e 000c0800 00000000
[  171.902292] sof-audio-pci-intel-apl 0000:00:0e.0: 0xbe04754c: 0dead000 00000000 84066828 ffff991b
[  171.902297] sof-audio-pci-intel-apl 0000:00:0e.0: 0xbe047550: c074903f ffffffff 85082800 ffff991b
[  171.902301] sof-audio-pci-intel-apl 0000:00:0e.0: 0xbe047554: 85079f00 ffff991b 8148c408 ffffffff
[  171.902306] sof-audio-pci-intel-apl 0000:00:0e.0: 0xbe047558: 83b59dc0 ffff991b 814cfa80 ffffffff
[  171.902311] sof-audio-pci-intel-apl 0000:00:0e.0: 0xbe04755c: 83b59dc0 ffff991b 00000000 00000000
[  171.902315] sof-audio-pci-intel-apl 0000:00:0e.0: error: waking up any trace sleepers
[  171.902447] sof-audio-pci-intel-apl 0000:00:0e.0: error: trace IO error

```

**Comment by lgirdwood** [comment] 2021-05-25 14:16
@XiaoyunWu6666 can you run with latest main as @keyonjie has merged some DAI fixes.

**Comment by XiaoyunWu6666** [comment] 2021-05-26 07:16
I am afraid not, error still occurs .
Let me run it with CI

**Comment by keyonjie** [comment] 2021-05-26 08:46
looks this could be dynamic pipeline related, can you try if reverting commit 426d7816e265 help?

**Comment by XiaoyunWu6666** [comment] 2021-05-26 09:19
i will check it later

**Comment by lgirdwood** [comment] 2021-05-26 10:06
@keyonjie this is a NULL ptr dereference at NULL + 0x5c.  Do we have the FW logs ?

**Comment by XiaoyunWu6666** [comment] 2021-05-26 16:38
> looks this could be dynamic pipeline related, can you try if reverting commit [426d781](https://github.com/thesofproject/sof/commit/426d7816e2652130efe060bbe5a12d01cef082c1) help?

i tried on ubuntu@jf-apl-up2-nocodec-1.
it can help

**Comment by lgirdwood** [comment] 2021-05-26 19:34
> > looks this could be dynamic pipeline related, can you try if reverting commit [426d781](https://github.com/thesofproject/sof/commit/426d7816e2652130efe060bbe5a12d01cef082c1) help?
> 
> i tried on ubuntu@jf-apl-up2-nocodec-1.
> it can help

ok, so it sounds like dynamic pipelines is freeing a resource, setting it to NULL and then we are reusing it.

**Comment by plbossart** [comment] 2021-05-26 19:44
we are not using dynamic pipelines for nocodec, isn't it @ranj063 ?

**Comment by ranj063** [comment] 2021-05-26 19:53
> we are not using dynamic pipelines for nocodec, isn't it @ranj063 ?

Yes, we are. I enabled it for some nocodec topologies already

**Comment by ranj063** [comment] 2021-05-26 19:54
I can look into this one. I cant imagine pause/release causing panics. It has to be something else.

**Comment by plbossart** [comment] 2021-05-26 19:56
FWIW the pause_push/release for SSPs seems completely broken, I can't figure out what the code does.

**Comment by marc-hb** [comment] 2021-06-01 16:47
Can we please partially revert the small, `apl-nocodec` bit of 426d7816e265 to get the tests passing again while leaving this bug open? I mean just this bit:

```diff
--- a/tools/topology/CMakeLists.txt
+++ b/tools/topology/CMakeLists.txt
@@ -30,7 +30,7 @@ set(TPLGS
        "sof-hda-generic-idisp\;sof-hda-generic-idisp\;-DCHANNELS=0\;-DDYNAMIC=1"
        "sof-hda-generic-idisp\;sof-hda-generic-idisp-2ch\;-DCHANNELS=2\;-DDMICPROC_FILTER1=eq_iir_coef_high>
        "sof-hda-generic-idisp\;sof-hda-generic-idisp-4ch\;-DCHANNELS=4\;-DDMICPROC_FILTER1=eq_iir_coef_high>
-       "sof-apl-nocodec\;sof-apl-nocodec"
+       "sof-apl-nocodec\;sof-apl-nocodec\;-DDYNAMIC=1"
        "sof-apl-keyword-detect\;sof-apl-keyword-detect"
        "sof-bdw-codec\;sof-bdw-rt286\;-DCODEC=RT286"
        "sof-bdw-codec\;sof-bdw-rt5640\;-DCODEC=RT5640"
```

**Comment by marc-hb** [comment] 2021-06-02 05:17
> Can we please partially revert the small, apl-nocodec bit of 426d781 to get the tests passing again while leaving this bug open?

Submitted in #4273 . See a different bug description fixed by the same revert there.

**Comment by ranj063** [comment] 2021-06-02 17:04
Like I mentioned, this issue not related to pause/release at all. Just testing playback simultaenously on PCM0 and PCM7 exposes the bug with dynamic pipelines. Our tests limit the number of simultaneous pipelines to 4, so we never test PCM0 and PCM7 together. Ideally the multiple-pipeline playback should have failed at the very first iteration if we had tested this combination.

**Comment by marc-hb** [comment] 2021-06-02 17:42
Indeed I can reproduce a severe crash with a mere `sof-test/test-case/multiple-pipeline-playback.sh -c 5` (which uses both PCM0 and PCM7) whereas `sof-test/test-case/multiple-pipeline-playback.sh -c 4` (the default) does not. Patch #4282 makes that panic go away.

The bug I described in #4273 seems different. It is not affected by the #4282 patch.

@XiaoyunWu6666 could you or someone else investigate our worrying lack of test coverage with respect to concurrent pipelines here?

**Comment by plbossart** [comment] 2021-06-02 17:44
I don't get the limitation @ranj063. we reduced the number of SSP tested due to memory requirements, why do the tests reduce concurrency between pipelines?

**Comment by plbossart** [comment] 2021-06-02 17:46
I also don't get what is common between PCM0 and PCM7, the patch in #4282 fixes problems when sharing components but PCM0 is an SSP and PCM7 HDMI. There should be nothing in common.

Confused.

**Comment by ranj063** [comment] 2021-06-02 17:52
![sof-apl-nocodec](https://user-images.githubusercontent.com/7766921/120528696-96582c80-c390-11eb-8142-e51bd19c1726.png)

**Comment by ranj063** [comment] 2021-06-02 17:53
@plbossart PCM0 and PCM7 are the playback pipelines that are connected at the mixer.

**Comment by plbossart** [comment] 2021-06-02 21:06
ok, thanks @ranj063. Not sure why we keep using silly numbering conventions or again using a bad mixer solution. Oh well.

**Closed** 2021-06-03 13:26 UTC
Labels: APL, I2S, P1, bug, dynamic pipeline, linux
