### ISSUE TITLE
[BUG] glitch in test 14_12_TestDemuxEchoSynchronizedStreamOperation8000Hz16b16b2ch

### ISSUE THREAD

**Issue by kkarask** [thesofproject/sof#4166] opened 2021-05-11 10:17 UTC
**Describe the bug**
Glitch was found in test 14_12_TestDemuxEchoSynchronizedStreamOperation8000Hz16b16b2ch

**Topology**
```
         pipe_plb
    +------------------------------------------------------+
    | +------+   +------+   +-------+   +------+   +-----+ |     +------+
    | | Host |-->| Buff |-->| DeMux |-->| Buff |-->| Dai |------>| SSPx |
    | +------+   +------+   +-------+   +------+   +-----+ |     +------+
    +---------------------------|--------------------------+        |
                                |                                   |
         pipe_cap               |                                   |
    +---------------------+     |                                   |
    | +------+   +------+ |     | echo ref                          |
    | | Host |<--| Buff |<------<                                   |
    | +------+   +------+ |                                         |
    +---------------------+                                         |
                                                                    |
                                                                    |
        pipe_cap                                                    |
    +-------------------------------+                               |
    | +------+   +------+   +-----+ |                               |
    | | Host |<--| Buff |<--| Dai |<--------------------------------<
    | +------+   +------+   +-----+ |
    +-------------------------------+
```

**To Reproduce**
Run test  14_12_TestDemuxEchoSynchronizedStreamOperation8000Hz16b16b2ch with Diagnostic driver 

**Reproduction Rate**
Sporadic.
Problem doesn't exist before 47d223c09ff5da56073f3590d14a64bde513358d

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * SOF: branch: main, hash: 47d223c09ff5da56073f3590d14a64bde513358d (SOF_FW_MASTER_01.01.00.2290)
    
2) Name of the platform(s) on which the bug is observed.
    * Platform: APL RVP
    
3) Test environment:
    BRANCH: master HASH:  7bc54a9c53346cea3dfc5bdedbc6a02e39597193

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/82518823/117786984-534de200-b246-11eb-8d4e-c95f77aecb19.png)

[14_12_TestDemuxEchoSynchronizedStreamOperation8000Hz16b16b2ch.zip](https://github.com/thesofproject/sof/files/6457843/14_12_TestDemuxEchoSynchronizedStreamOperation8000Hz16b16b2ch.zip)

**Comment by lgirdwood** [comment] 2021-05-13 12:12
Duplicate of simpler https://github.com/thesofproject/sof/issues/4076

**Comment by kkarask** [comment] 2021-06-24 07:20
Glitch was visible on TGL platform with Demux component too.
Hash: 7cc9a80ab8cc5ea70c190c266a310f60fcaeea80 (SOF_FW_MASTER_01.01.00.2432)

![image](https://user-images.githubusercontent.com/82518823/123219073-c5b01400-d4cc-11eb-883a-950efca05b0a.png)


[TGL.zip](https://github.com/thesofproject/sof/files/6707094/TGL.zip)

**Comment by lgirdwood** [comment] 2021-06-25 13:27
Thanks @kkarask - btw, I'm assuming that the timer starts for all your audacity dumps at the start of the captured wave file ? I'm just trying to confirm as this looks like a glitch mid flow after 4.34 seconds ? (and not glitching at the start)

**Comment by kkarask** [comment] 2021-06-28 12:00
@lgirdwood While pipelines are working pause and resume operation are done on playback and echo reference streams. Glitch is visible between the streams during these operations.

![image](https://user-images.githubusercontent.com/82518823/123632492-48600880-d818-11eb-959c-8c293a6d0292.png)

**Comment by lgirdwood** [comment] 2021-06-30 10:54
@kkarask thanks, I'm forming an opinion now that we probably have a timing difference in IPC messages and stream DMA operations between diagnostic driver and Linux driver. Is there anyway you can dump the log sections relating to the glitches only with the timestamps of IPC and stream DMA programming/IRQs to compare against the kernel dmesg. @slawblauciak what do you think ?

**Comment by kkarask** [comment] 2021-07-15 09:39
Glitches are visible in test 14_08_TestDemuxEchoSynchronized48000Hz32b32b4ch without start/stop operations . The topology is the same. 


WHL RVP platform (near the start of the capture:)
![image](https://user-images.githubusercontent.com/82518823/125765990-77ef6b6d-e317-4bc1-ab91-951c9ea94dea.png)

APL RVP platform (the whole file):
![image](https://user-images.githubusercontent.com/82518823/125766382-2c618145-ee3c-45a8-a6b4-4c1a266d94c3.png)

Both reproduction rate: 1/75.

**Comment by antonirx** [comment] 2023-01-05 10:18
unsupported platform
on TGL issue does not occur
Tested FW hash: 4943aaa

**Closed as completed** 2023-01-05 10:18 UTC
Labels: bug, duplicate, APL, WHL, ICL, TGL, diagnostic driver
