### ISSUE TITLE
[BUG]TGLU-RVP-NOCODEC-CI dsp panic/ipc timed out when  multiple-pause-resume 

### ISSUE THREAD

**Issue by 1994lwz** [thesofproject/sof#4667] opened 2021-08-23 02:57 UTC
**Describe the bug:**
TGLU-RVP-NOCODEC-CI dsp panic/ipc timed out  when do the multiple-pause-resume test.
found in inner daily 5994

**To Reproduce**
TPLG=/lib/firmware/intel/sof-tplg/sof-tgl-nocodec-ci.tplg ~/sof-test/test-case/multiple-pause-resume.sh -r 25

**Reproduction Rate**
not 100%

**Environment**
Kernel Branch: topic/sof-dev
Kernel Commit: af102fc2
SOF Branch: main
SOF Commit: db8ee55b528a
Topology:/lib/firmware/intel/sof-tplg/sof-tgl-nocodec-ci.tplg
Platform: TGLU-RVP-NOCODEC-CI-01

**Screenshots or console output**
[console]
```
=== PAUSE ===                                                            
(3/25) pcm'smart-nocodec' cmd'aplay' id'0': Wait for 20 ms before resume
 aplay: do_pause:1545: pause push error: Connection timed out
                                                                          

=== PAUSE ===                                                            
(9/25) pcm'Port0' cmd'aplay' id'2': Wait for 27 ms before resume
 aplay: do_pause:1545: pause push error: Connection timed out
```
[dmesg]
```
[dmesg.txt](https://github.com/thesofproject/sof/files/7028842/dmesg.txt)

[ 3421.302411] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 3
[ 3421.302413] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60060000: GLB_STREAM_MSG: TRIG_PAUSE
[ 3421.302619] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x60060000: GLB_STREAM_MSG: TRIG_PAUSE
[ 3421.303062] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x180]=0x20240000 successful
[ 3421.318297] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: pcm: trigger stream 2 dir 0 cmd 4
[ 3421.318817] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x160]=0x2014001e successful
[ 3421.318821] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60070000: GLB_STREAM_MSG: TRIG_RELEASE
[ 3421.319246] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x60070000: GLB_STREAM_MSG: TRIG_RELEASE
[ 3421.325190] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error : DSP panic!
[ 3421.325194] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: panic: dsp_oops_offset 788480 offset 788480
[ 3421.325195] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump start ]------------
[ 3421.325212] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: status: fw entered - code 00000005
[ 3421.325300] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: runtime exception
[ 3421.325302] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: trace point 00004000
[ 3421.325303] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: panic at :0
[ 3421.325305] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: DSP Firmware Oops
[ 3421.325307] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: Exception Cause: LoadProhibitedCause, A load referenced a page mapped with an attribute that does not permit loads
[ 3421.325308] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: EXCCAUSE 0x0000001c EXCVADDR 0xc0000000 PS       0x00060b25 SAR     0x00000000
[ 3421.325310] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: EPC1     0xbe02dee7 EPC2     0xbe02d462 EPC3     0x00000000 EPC4    0x00000000
[ 3421.325312] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: EPC5     0x00000000 EPC6     0x00000000 EPC7     0x00000000 DEPC    0x00000000
[ 3421.325313] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: EPS2     0x00060f20 EPS3     0x00000000 EPS4     0x00000000 EPS5    0x00000000
[ 3421.325315] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: EPS6     0x00000000 EPS7     0x00000000 INTENABL 0x00000000 INTERRU 0x00000222
[ 3421.325316] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: stack dump from 0xbe280cb0
[ 3421.325318] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: 0xbe280cb0: 00000000 00000000 00000000 00000000
[ 3421.325320] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: 0xbe280cb4: 7e051b61 be280d30 be0a0e80 9e0a0fe4
[ 3421.325321] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: 0xbe280cb8: f4b73c00 d7450508 1cac7828 ffff8fd4
[ 3421.325323] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: 0xbe280cbc: 000c0800 00000000 1cac7828 ffff8fd4
[ 3421.325324] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: 0xbe280cc0: 1cac7828 ffff8fd4 00000092 00000000
[ 3421.325326] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: 0xbe280cc4: 234cc400 ffff8fd4 2f42a000 ffff8fd4
[ 3421.325327] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: 0xbe280cc8: f4b73c00 d7450508 b58cffa0 ffffffff
[ 3421.325328] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: 0xbe280ccc: 01d19080 ffff8fd4 b588d710 ffffffff
[ 3421.325330] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump end ]------------
[ 3421.325371] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: trace IO error
```

**Comment by XiaoyunWu6666** [comment] 2021-08-24 06:39
duplicate of #4606 
When multiple-pause-resume , sometimes xrun happened with dmesg varying

**Closed by XiaoyunWu6666** 2021-08-24 06:39 UTC
Labels: bug, TGL, multicore, Intel Linux Daily tests, stress CI multicore tplg
