### ISSUE TITLE
Firmware oops when pulseaudio is enabled

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#278] opened 2018-08-30 08:47 UTC
Pulseaudio will cause firmware oops on CNL and BYT
[dmesg.log](https://github.com/thesofproject/sof/files/2335366/dmesg.log)
[rmbox-t.log](https://github.com/thesofproject/sof/files/2335368/rmbox-t.log)

How to reproduce:
1.  make sure pulseaduio is enable(ls /usr/bin/pulseaudio)
2. check the dmesg after system is booted.

**Comment by lgirdwood** [comment] 2018-08-30 09:31
duplicate of #210

**Comment by ZhendanYang** [comment] 2018-09-10 06:16
duplicate of #274 .

**Comment by ZhendanYang** [comment] 2018-09-28 07:04
Test with latest code base, this issue can't reproduce
Test env:
sof master: 299ccbc
sof tool: 60c3937
kernel: sof-dev 51ebd5d

**Closed by ZhendanYang** 2018-09-28 07:04 UTC
Labels: BYT, CNL, P3, br-master, bug, duplicate, regression
