### ISSUE TITLE
UP2 - nocodec: Failed on config DMIC DAI

### ISSUE THREAD

**Issue by Jiangxinx** [thesofproject/sof#716] opened 2018-12-14 08:21 UTC
Summary:
Failed to set DAI config for DMIC0 on UP2 w/o codec.
This issue is similar to #660 ,  seems to be a firmware regression.

dmesg:
[    4.298247] sof-audio sof-audio: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[    4.298583] sof-audio sof-audio: error: ipc error for 0x80010000 size 0xc
[    4.298601] sof-audio sof-audio: error: failed to set DAI config for DMIC0
[    4.298606] sof-audio sof-audio: ASoC: physical link loading failed
[    4.298610] sof-audio sof-audio: error: tplg component load failed -5
[    4.298633] sof-audio sof-audio: error: failed to load DSP topology -22
[    4.298638] sof-audio sof-audio: ASoC: failed to probe component -22
[    4.298674] sof-nocodec sof-nocodec: ASoC: failed to instantiate card -22
[    4.298687] sof-nocodec sof-nocodec: Topology forgot to remove link Port0?
[    4.298689] sof-nocodec sof-nocodec: Topology forgot to remove link Port1?
[    4.298691] sof-nocodec sof-nocodec: Topology forgot to remove link Port3?
[    4.298694] sof-nocodec sof-nocodec: Topology forgot to remove link Port5?
[    4.298696] sof-nocodec sof-nocodec: Topology forgot to remove link DMIC01?
[    4.298780] sof-nocodec: probe of sof-nocodec failed with error -22

Test steps:
aplay -l
aplay: device_list:270: no soundcards found...

Test env:
sof master: 78f13ed4
kernel sof-dev: 48d46cba
tplg: sof-apl-nocodec.tplg

**Comment by zhuyingjiang** [comment] 2018-12-17 07:42
[ 4.298583] sof-audio sof-audio: error: ipc error for 0x80010000 size 0xc
[ 4.298601] sof-audio sof-audio: error: failed to set DAI config for DMIC0
the error is the same as https://github.com/thesofproject/linux/issues/442

**Comment by lgirdwood** [comment] 2018-12-17 20:33
@zhuyingjiang have you tried with todays HEAD as there were update merged for IPC ?

**Comment by libinyang** [comment] 2018-12-19 01:19
@Jiangxinx 
Can't reproduce this issue on the latest kernel and sof. Please test on the latest kernel and close this issue if can't reproduce

**Closed as completed** 2018-12-19 03:23 UTC
Labels: bug, APL
