### ISSUE TITLE
[BUG] Keyword detection notification timeout occured

### ISSUE THREAD

**Issue by kkarask** [thesofproject/sof#4168] opened 2021-05-11 11:06 UTC
**Describe the bug**
Keyword detection notification timeout was found in test 13_00_TestKdProductionGLK

**Topology**
```
+----------+   +------------------+
|    OS    |-->|   AUDIO DEVICE   |---------------------+
+----------+   +------------------+                     |
                                                        |
           +-------------------------+                  |
+--------+ | +---+   +-----+   +---+ |                  |
|KD Dummy|<->|Buf|<->|ChSel|<->|Buf|<->-+               |
+--------+ | +---+   +-----+   +---+ |  |  pipe_cap     |
           +-------------------------+  |               |
                     +------------------+    FIFO B     |
+--------------------|--------------------------------+ |
|+----+  +------+  +---+  +---+  +---+  +---+  +----+ | |
||Host|<-|Buffer|<-|Kpb|<-|Buf|<-|Vol|<-|Buf|<-|DMIC|---+
|+----+  +------+  +---+  +---+  +---+  +---+  +----+ | |
+-----------------------------------------------------+ |
                                                        |
                                FIFO A                  |
                 +------------------------------------+ |
                 |+----+  +---+  +---+  +---+  +----+ | |
                 ||Host|<-|Buf|<-|Vol|<-|Buf|<-|DMIC|---+
                 |+----+  +---+  +---+  +---+  +----+ |
                 +------------------------------------+

       +--------------------------------+
+----+ | +---+  +---+  +---+  +-------+ |
|Host|-->|Buf|->|Vol|->|Buf|->|SSP Dai|---+
+----+ | +---+  +---+  +---+  +-------+ | |
       +--------------------------------+ |
                                          |
       +------------------+               |
+----+ | +---+  +-------+ |               |
|Host|<--|Buf|<-|SSP Dai|<----------------+
+----+ | +---+  +-------+ |
       +------------------+
```

**To Reproduce**
Run test 13_00_TestKdProductionGLK with Diagnostic driver

**Reproduction Rate**
1/75

**Environment**
1) Firmware branch name and commit
    * SOF: Branch: main, Hash: 37d97d4357b34ba2f5f59aa575740d27f2a031c7, Tag: v1.8-rc1
    Problem doesn't exist before: 37d97d4

2) Name of the platform(s) on which the bug is observed.
    * Platform: APL RVP
    
3) Test environment:
    Branch: master Hash: 7bc54a9c53346cea3dfc5bdedbc6a02e39597193

Logs:
[13_00_TestKdProductionGLK.zip](https://github.com/thesofproject/sof/files/6458679/13_00_TestKdProductionGLK.zip)

**Comment by lgirdwood** [comment] 2021-05-24 12:00
@kkarask is the SSP loopback pipeline running when this failure occurs ?
@mrajwa fyi.

**Comment by kkarask** [comment] 2021-05-24 12:44
@lgirdwood yes, SSP pipeline is running during the test

**Comment by lgirdwood** [comment] 2021-05-24 14:56
@kkarask ok, have you been able to reproduce this at all with the kernel driver ? @slawblauciak fyi - could impact TGL13.

**Comment by juimonen** [comment] 2021-05-24 15:28
@kkarask are you sure about the "problem doesn't exists before" -part as that commit really can't have too much to do with this issue? We should really bisect the fw and try to find the actual commit. I know this is a really difficult one, but I would assume the commit should be related more likely directly to SSP or fw scheduling etc.

I can't reproduce the loopback issues with linux driver and I can't get the slimdriver very easily running in linux...

**Comment by kkarask** [comment] 2021-05-25 10:36
@lgirdwood I'm not able to reproduce it using kernel. 
@juimonen Sorry for misleading, I found keyword problem also here:  5ca0e9bba3e6da8abab7faf4577aa6683200bf41
Logs:
[13_00_TestKdProductionGLK.zip](https://github.com/thesofproject/sof/files/6538547/13_00_TestKdProductionGLK.zip)

**Comment by lgirdwood** [comment] 2021-05-27 11:00
@kkarask thanks for the confirmation, I think we need to say that this could be a bug with Slim driver since we cant reproduce it with the Linux driver. We can re-open if it proves otherwise but lets close it now.

**Closed by lgirdwood** 2021-05-27 11:00 UTC
Labels: APL, Not Reproducible with Driver, bug, won't fix

**Comment by zrombel** [comment] 2021-05-27 13:26
@lgirdwood: I wouldn't be so sure about closing this bug. KD is problematic feature and some issues are visible only on slim driver but it may indicate that there is some problem in KD logic or some corner case and I think that someone should take a look at this as it may show it self in future. @kkarask please take a look at this issue and report it if it keeps on failing.

**Comment by lgirdwood** [comment] 2021-05-27 15:15
> @lgirdwood: I wouldn't be so sure about closing this bug. KD is problematic feature and some issues are visible only on slim driver but it may indicate that there is some problem in KD logic or some corner case and I think that someone should take a look at this as it may show it self in future. @kkarask please take a look at this issue and report it if it keeps on failing.

I agree, but this cant yet be reproduced on the Linux driver - it may be differences in timing or slim driver flow that make it reproducible on slim driver only. I would also agree that we keep testing as future FW changes make may it reproducible on the Linux driver (and hence an end user issue).

**Comment by kkarask** [comment] 2021-06-08 10:58
I would like to add that this problem is visible every day in regression tests on APL.
