### ISSUE TITLE
[BUG][MTL-002] Recorded file from echo-reference dev has distortion and noise

### ISSUE THREAD

**Issue by yongzhi1** [thesofproject/sof#6657] opened 2022-11-23 22:43 UTC
**Describe the bug**
Run echo ref unit test with NOCODEC config, the captured file shows distortion and noise when examined on Audacity. 

**To Reproduce**
Start playback first:
```
aplay -Dhw:0,0 -c2 -r48000 -fS16_LE /home/sample.wav
```
Run capture and check the captured file on desktop:
```
arecord -Dhw:0,13 /home/loop.wav -c2 -r48000 -fs16_le -d10 
```

**Reproduction Rate**
100%

**Expected behavior**
The issue is not reproducible with closed src ACE FW.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: https://github.com/bardliao/linux/commits/echo-reference-nocodec
    * SOF: https://github.com/thesofproject/sof/tree/mtl-002-drop-stable
2) Name of the topology file
    * Topology: https://github.com/bardliao/sof/commits/test-echo-reference-nocodec-2

![sof-mtl-nocodec](https://user-images.githubusercontent.com/19287706/203659287-5d25be26-8ef2-45cc-b79f-b4545d7694e8.png)

3) Name of the platform(s) on which the bug is observed.
    * Platform: MTL-RVP

**Screenshots or console output**
[mtrace-echo-ref-mtl-002.txt](https://github.com/thesofproject/sof/files/10079534/mtrace-echo-ref-mtl-002.txt)
https://user-images.githubusercontent.com/19287706/203658196-f7212407-3407-497d-b893-ab293443ce5d.mp4

**Comment by lgirdwood** [comment] 2022-11-25 12:01
> Run echo ref unit test with NOCODEC config, the captured file shows distortion and noise when examined on Audacity.

@yongzhi1 can you take a screenshot of the audacity waveform and also attach a small raw PCM clip. Compressed audio cant be used to root cause distortion.

**Comment by mengdonglin** [comment] 2022-11-28 11:44
@yongzhi1 Which Platform and codec are you using in the test?

**Comment by yongzhi1** [comment] 2022-11-28 17:27
Hi @lgirdwood, here is the screenshot for the waveform, the lower track was captured with ACE, in both cases LR_48k.wav was used

![Screenshot from 2022-11-28 11-16-17](https://user-images.githubusercontent.com/19287706/204341006-e4fe71ad-e85e-4412-98b3-0616f1922720.png)
And the captured file [loop-mtl-002.zip](https://github.com/thesofproject/sof/files/10106116/loop-mtl-002.zip)

**Comment by lgirdwood** [comment] 2022-11-30 13:39
@kfrydryx @mengdonglin sounds like some clipping/distortion on the signal. Does not look like a DMA issue, but maybe format conversion or signal clipping in the copier ?

**Comment by mengdonglin** [comment] 2022-12-01 07:55
@yongzhi1 @kfrydryx @lgirdwood Deprioritize this issue after sync with @bardliao . Current driver support for echo-reference is a temporary solution, and is being re-implemented. Let's test the new implementation when it's ready. Thanks!

**Comment by keqiaozhang** [comment] 2022-12-05 02:42
Will test EC in new implementation when it's ready, closing this one.

**Closed by keqiaozhang** 2022-12-05 02:42 UTC
Labels: bug, P3, MTL
