### ISSUE TITLE
[CML]IPC timed out, error: volume put failed to resume -22 (60%)

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/sof#1285] opened 2019-04-19 10:35 UTC
**Describe the bug**
IPC timed out, error: volume put failed to resume -22. 

**To Reproduce**
Scenario A:
"sudo  reboot" to reboot unit.  [Frequency:60%]

Scenario B:
Volume change stress test, error occurred  after changing about 2000 times.

**Expected behavior**
.Boot up normally without timeout issue.

Environment
Kernel Repo:
https://github.com/RanderWang/linux/commits/cml-validation-20190419
Made from:
RanderWang/linux@2de29fa

RanderWang/linux@d04ccf4
RanderWang/linux@bfb0729
RanderWang/linux@8a2b13a
RanderWang/linux@63ceb8f
RanderWang/linux@db89510
RanderWang/linux@066e6f4
RanderWang/linux@bfb3fcb
RanderWang/linux@edc012c
RanderWang/linux@a9f0431
RanderWang/linux@d5113b0
RanderWang/linux@aeccfd5
RanderWang/linux@22999bd
RanderWang/linux@c827ffb
Sof Repo: https://github.com/bardliao/sof/tree/whl-daliy-20190419
Made from: bardliao@ 4c6f6f7

bardliao/sof@90a6efd
bardliao/sof@5ef0713
bardliao/sof@50bd96d
bardliao/sof@fdf1eda
bardliao/sof@f135dd9
bardliao/sof@e8d5622

dmesg:
```
[   31.078242] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x30030000: GLB_TPLG_MSG: COMP_CONNECT
[   31.078247] sof-audio-pci 0000:00:1f.3: ipc tx: 0x30030000: GLB_TPLG_MSG: COMP_CONNECT
[   31.078321] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x30030000: GLB_TPLG_MSG: COMP_CONNECT
[   31.078326] sof-audio-pci 0000:00:1f.3: ipc tx: 0x30030000: GLB_TPLG_MSG: COMP_CONNECT
[   31.078403] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x30030000: GLB_TPLG_MSG: COMP_CONNECT
[   31.078408] sof-audio-pci 0000:00:1f.3: ipc tx: 0x30030000: GLB_TPLG_MSG: COMP_CONNECT
[   31.078484] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x30030000: GLB_TPLG_MSG: COMP_CONNECT
[   31.078489] sof-audio-pci 0000:00:1f.3: ipc tx: 0x30030000: GLB_TPLG_MSG: COMP_CONNECT
[   31.078566] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x30030000: GLB_TPLG_MSG: COMP_CONNECT
[   31.078571] sof-audio-pci 0000:00:1f.3: ipc tx: 0x30030000: GLB_TPLG_MSG: COMP_CONNECT
[   31.078856] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x30030000: GLB_TPLG_MSG: COMP_CONNECT
[   31.078865] sof-audio-pci 0000:00:1f.3: ipc tx: 0x30030000: GLB_TPLG_MSG: COMP_CONNECT
[   31.379855] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x30030000 size 16
[   31.379870] sof-audio-pci 0000:00:1f.3: status: fw entered - code 00000005
[   31.380085] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0x00000000 trace 0x00004000
[   31.380089] sof-audio-pci 0000:00:1f.3: error: waking up any trace sleepers
[   31.380095] sof-audio-pci 0000:00:1f.3: error: failed to load route sink  control none source 
[   31.380098] sof-audio-pci 0000:00:1f.3: error: failed to restore pipeline after resume -110
[   31.380105] sof-audio-pci 0000:00:1f.3: error: volume put failed to resume -110
[   31.380225] sof-audio-pci 0000:00:1f.3: error: volume put failed to resume -22
[   31.380267] sof-audio-pci 0000:00:1f.3: error: volume put failed to resume -22
[   31.380300] sof-audio-pci 0000:00:1f.3: error: volume put failed to resume -22
[   31.380333] sof-audio-pci 0000:00:1f.3: error: volume put failed to resume -22
[   31.380367] sof-audio-pci 0000:00:1f.3: error: volume put failed to resume -22
[   31.380398] sof-audio-pci 0000:00:1f.3: error: volume put failed to resume -22
[   31.578986] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[   31.579013] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[   37.383576] iwlwifi 0000:00:14.3: BIOS contains WGDS but no WRDS
[   38.995561] ax88179_178a 1-1:1.0 enx000ec6a1e622: ax88179 - Link status is: 1
[   39.003737] IPv6: ADDRCONF(NETDEV_CHANGE): enx000ec6a1e622: link becomes ready
[   42.525702] systemd-journald[1678]: File /var/log/journal/11b21a64962c4ebe844439e9a5e72250/user-1001.journal corrupted or uncleanly shut down, renaming and replacing.
[   44.163640] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 5:0
[   46.275401] sof-audio-pci 0000:00:1f.3: pcm: open stream 0 dir 1
[   46.275405] sof-audio-pci 0000:00:1f.3: error: pcm open failed to resume -22
[   46.275410] sof-audio-pci 0000:00:1f.3: ASoC: can't open component 0000:00:1f.3: -22
[   46.275413]  HDA Analog: ASoC: failed to start FE -22
[   46.276613] sof-audio-pci 0000:00:1f.3: pcm: open stream 0 dir 0
[   46.276616] sof-audio-pci 0000:00:1f.3: error: pcm open failed to resume -22
[   46.276619] sof-audio-pci 0000:00:1f.3: ASoC: can't open component 0000:00:1f.3: -22
[   46.276622]  HDA Analog: ASoC: failed to start FE -22
[   46.277585] sof-audio-pci 0000:00:1f.3: pcm: open stream 0 dir 1
[   46.277587] sof-audio-pci 0000:00:1f.3: error: pcm open failed to resume -22
[   46.277591] sof-audio-pci 0000:00:1f.3: ASoC: can't open component 0000:00:1f.3: -22
[   46.277593]  HDA Analog: ASoC: failed to start FE -22
[   46.277747] sof-audio-pci 0000:00:1f.3: pcm: open stream 0 dir 1
[   46.277750] sof-audio-pci 0000:00:1f.3: error: pcm open failed to resume -22
[   46.277753] sof-audio-pci 0000:00:1f.3: ASoC: can't open component 0000:00:1f.3: -22
[   46.277756]  HDA Analog: ASoC: failed to start FE -22
[   46.277960] sof-audio-pci 0000:00:1f.3: pcm: open stream 0 dir 0
[   46.277962] sof-audio-pci 0000:00:1f.3: error: pcm open failed to resume -22
[   46.277965] sof-audio-pci 0000:00:1f.3: ASoC: can't open component 0000:00:1f.3: -22
[   46.277968]  HDA Analog: ASoC: failed to start FE -22
[   46.278118] sof-audio-pci 0000:00:1f.3: pcm: open stream 0 dir 0
[   46.278120] sof-audio-pci 0000:00:1f.3: error: pcm open failed to resume -22
[   46.278123] sof-audio-pci 0000:00:1f.3: ASoC: can't open component 0000:00:1f.3: -22
[   46.278126]  HDA Analog: ASoC: failed to start FE -22
[   49.279931] rfkill: input handler disabled
```

[dmesg_ipcTimeOut_volume.log](https://github.com/thesofproject/sof/files/3097821/dmesg_ipcTimeOut_volume.log)
[logger_ipcTimeOut_volume.log](https://github.com/thesofproject/sof/files/3097822/logger_ipcTimeOut_volume.log)

**Comment by lgirdwood** [comment] 2019-04-19 13:39
@ClarexZhou this looks like a duplicate of two issues. Scenario A is a duplicate of #1254 and scenario B #1263

**Closed by lgirdwood** 2019-04-19 13:39 UTC
Labels: bug
