### ISSUE TITLE
platform: merge platform.h and plat_cfg.h

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof#1080] opened 2019-03-05 12:05 UTC
Both files do the same thing so merge them.

**Comment by tlauda** [comment] 2019-03-05 12:08
@lgirdwood platcfg.h is also used in asm code, so it might not be that easy.

**Comment by lgirdwood** [comment] 2019-03-05 13:59
ifdef ASSEMBLY etc should fix assembly usage.

**Comment by abonislawski** [comment] 2019-03-15 12:26
It is more tricky because it will be included, for example, from base_module.c (memory.h->platform.h) where ASSEMBLY def will not work as for .S files

So, it would be necessary to make whole platform.h working (without ifdef ASSEMBLY) which means moving some problematic things from platform.h to another already included files at this stage. Not sure if worth it.

OR instead of #ifdef ASSEMBLY use something like #ifdef sof_target (if it is possible) which will effectively split the file in a needed way but Im not sure if it is a better way than two files.

Maybe someone have a better idea?

**Comment by lgirdwood** [comment] 2019-03-15 15:38
> It is more tricky because it will be included, for example, from base_module.c (memory.h->platform.h) where ASSEMBLY def will not work as for .S files

Not following. All .S files must be built with -DASSEMBLY meaning we can move any C code behind an ifdef. Same goes for linker script usage as we define -DLINKER now too.

i.e. platcfg.h
```
/* all generic macros here */
...

/* All C stuff here */
#if  !defined(ASSEMBLY) && !defined(LINKER)

/* C macros and declarations here */

#endif
```

**Comment by abonislawski** [comment] 2019-03-19 10:42
Yes, thats right. Maybe I have explained this not good enough, but merging this two files with if !defined(ASSEMBLY) is very easy but the problem is to compile it :) Because the includes flow will be different now (in platform.h we have some extra includes comparing to platcfg.h),
You can check working version for APL+CNL+ICL here:
https://github.com/abonislawski/sof/commit/65f83bf818b044ae40fc25a8291ab3750da3f713

Im not sure if the includes should look like this, maybe there will be needed bigger rework?

**Comment by lgirdwood** [comment] 2019-03-19 15:17
The patch looks OK to me, what errors do you see when building ?

**Comment by abonislawski** [comment] 2019-03-20 13:08
This one is working without errors but I had to play a little with includes flow (without that there were errors like implicit declaration or undefined reference, etc.).
In some places I didnt just replaced platcfg.h with platform.h, for example in memory.h platcfg.h was deleted but added platform.h to linker script. In alloc.h I have replaced memory.h with platform.h. Also deleted in cpu.h without adding platform.h
Thats why Im not sure if thats the correct way, please check carefully. If its okay then I will open a PR

**Comment by lgirdwood** [comment] 2019-03-21 15:20
@abonislawski please do send a PR, this way CI will give it a good test too. :)

**Comment by abonislawski** [comment] 2019-03-25 08:09
Done in PR #1171 so can be closed

**Closed by abonislawski** 2019-03-25 08:09 UTC
Labels: enhancement
